### ISSUE TITLE
Sigil of Concentration buff tracking

### ISSUE THREAD

**Issue by BackIsBachus** [baaron4/GW2-Elite-Insights-Parser#105]
**Is your feature request related to a problem? Please describe.**
When trying to study and provide feedback on a chrono rotation with the big chart (the one visible on the 1st panel while viewing a specific player with the possibility to display a lot fo different buffs) it is hard to keep track of a Sigil of Concnetration buff and the Weapon swap yellow tile is really hard to see unless you are very zoomed in.

**Describe the solution you'd like**
Detect the Sigil of Concentration buff if possible and allow its display like all the other buffs if possible. This would help know if a buffing skill has been used while the Sigil buff was up.

**Describe alternatives you've considered**
If the Sigil of Concentration buff is not trackable assume that a Superior Sigil is used and add a "simulated" buff for 7 seconds after a weapon swap.

**Comment by EliphasNUIT** [comment]
Done, I only did it for superior sigil though, I don't have any logs where major/minor sigils were used so I could not find their id but I believe this should be enough.

**Comment by BackIsBachus** [comment]
The buff if the same I think [Masterful Concentration](https://wiki.guildwars2.com/wiki/Masterful_Concentration) , only the duration is different.

Many thanks for the quick integration!
