### ISSUE TITLE
Fractal Mechanics (List and call for opinions) or "What is worth tracking?"

### ISSUE THREAD

**Issue by LunusLupus** [baaron4/GW2-Elite-Insights-Parser#121]
Thanks to Micca (dps.report dev), I was provided with some extensive logs containing almost every trackable fractal mechanic (and a lot of, sadly, untrackable ones), so I tried to compile a list of what we could track and ask for opinions on what should be included. It's totally possible (and maybe even likely) that a mechanic was missed. Feel free to mention it here!
A lot of mechanics in fractals have a multitude of IDs for the exact same attack (up to ten, e.g. for different phases), which makes it easy to miss one or two in a specific run.
Everthing I question being worthwile is not planned to be tracked atm (according to my opinion, ofc).

**General:** 
In case not everyone is aware: HP% based hits aren't tracked by arc due to the way the server handles those attacks. This can and will not change unless ANet changes their internal coding (which I would say is less likely than getting build templates and 6 wings per year).
Basically all _shockwaves_ in fractals seem to deal no damage and are only tracked when interrupting someone. Could maybe include a Mechanictype for that (or solve it via the Special condition checking the 'result' variable) if it's deemed worthy. Will not register all hits though as mentioned.
_Fractal Vindicators_: Spawn detection is what I suggest (and implemented), but would like second opinions on that. This will create a new line in the (second) mechanics table for every vindicator spawning, making it quite long on bad fights. Not that much of an issue but grouping might be an option for those.
_Oneshot Mechanics_: As those are in general HP% based, none of those can be tracked directly. There are some workarounds for some of them (e.g. failed to break defiance bar).

**Implemented Mechanics are crossed out**

**99 CM**:
_Toxic Sickness_: Being hit by the cone vomit from a party member causes this ID to fire. Sadly, ONLY recorded for the PoV so I excluded it for now.

**MAMA**:
~~_Blastwave_: Spinning Knockback, applies burning~~
~~_Shoot_: Toxic green balls (and standing in their AoE)~~
~~_Red Balls_: Normal red balls she shoots before/after green ones but same animation/pattern. Maybe overkill to track those?~~
~~_Grenade Barrage_: Multitude of red balls launched into all directions, showing their impact with small orange circles. Worthwile?~~
~~_Explosive Impact_: Jump attack from Watchknights.~~
~~_Extraction_: Pulling Circle mechanic from Watchknights.~~
_Arkks Bubble_: While there is a buff that can be tracked for standing inside the bubble, it is only tracked for the PoV again. Decided to exclude it for now.
~~_Leap_: MAMA jumps onto a target releasing 3 shockwaves and dealing massive damage.~~
~~_Tantrum_: Double swing followed by half circle slam and three cone slams. Sadly, these are all on the same ID.~~
~~_Sweeping Strikes_: Many rapid swings in front of MAMA (only happens in the last phase).~~
~~_Nightmare Miasma_: Poisonous Goo from the expanding circle below 33% boss HP.~~
~~_Homing Grenades_: Similar to grenade barrage, but these seek a target and bounce twice after impact.~~
~~_Cascade of Torment_: Rings popping up in a set pattern below MAMA.~~
~~_Knight's Daze_: Dazing attack by the Watchknights. Worth tracking?~~
A couple more IDs that I couldn't link to any specific remarkable attack.

**Siax**:
~~_Tail Lash_: Tail attack~~
~~_Vile Spit_: Green poisonous circles.~~
~~_Nightmare Hallucination_: Only trackable via spawn, the person hit doesn't seem to be tracked.~~
~~_Cascade of Torment_: Rings (same as on MAMA)~~
_Normal red balls_: HP%, not trackable
~~_Fixation_: targeted by a Volatile Hallucination~~
_Volatile Expulsion_: Explosion of Volatile Hallucination, HP%, not trackable, could be circumvented by the condition application, if desired?
~~_Caustic Explosion_: The CC phase and the  four add phase. Both tracked by taking too long despite being HP%.~~

**Ensolyss**:
~~_Lunge_: Charge by Ensolyss or hallucinations in the last phase. Different IDs but I grouped them as the same mechanic.~~
~~_Upswing_: Split in two parts, the big orange circle jump and the explosion of the summoned illusions afterwards.~~
_Arkk Bubble_: Same Issue as on MAMA
~~_Nightmare Miasma_: Poisonous Goo, similar to the one on MAMA, grouped all IDs together.~~
~~_Caustic Explosion_: After capture phase defiance bar. Tracked if failed by taking too long. Also, the knockbacks (yellow arena quarters in hourglass constellation) during that phase are tracked on a different ID.~~
~~_Nightmare Devastation_: Starting the attack that is only protected inside Arkk's Bubble.~~
~~_Tail Lash_: Tail attack~~
_Serpent Strikes_: Basically auto attacks, worth tracking?
_Bullets_: All attacks during the circle capture phase are HP% based and thus not trackable.
~~_Caustic Grasp_: Platform wide pull~~
~~_Tormenting Blast_: Two yellow quarter circle attacks in quick succession that deal massive damage and knock back.~~
~~_Rampage_: Arrows in all directions, spawning knocking bubbles in rotating order while pulling party members into the middle~~
Also a couple of IDs that are sometimes named but hard to place and don't seem to fall under any category.

**100CM**:
**Skorvald**:
~~_Horizon Strike_: Pizza shapes that spawn and trigger in rotating order~~
~~_Crimson Dawn_: Last part of Horzion Strike (almost full platform is covered)~~
_Warp_: Jumping to a player that has been marked with a bomb above his head. Seems to not deal damage and isn't easily trackable.
~~_Spiral Strike_: Attack directly after Warp.~~
~~_Punshing Kick_: Single purple line knock back~~
~~_Cranial Cascade_: 3 purple lines knock back~~
~~_Focused Anger_: Large Cone knock back (crosshair overhead beforehand)~~
~~_Radiant Fury_: Expanding circles under all players, inflicting burning on every party member hit~~
~~_Solar Cyclone_: Spinning Knockback attack (via purple lines) in the last phase~~
~~_Blinding Radiance_: Feared by the overhead eye. Only trackable via the fear (so prevented by stability), not the direct hit of damage as that one is HP% based.~~
_Beaming Smile (Death Ray)_: HP% based
~~_Fixate_: Fixated by a solar bloom~~
_Explode_: Hit by the solar bloom CC, only shows up if it interrupts something as the damage seems HP% based, not tracked atm
~~_Combustion Rush_: Charging over the platform, knocking back players~~
~~_Wave of Mutilation_: Knockback jump in last phase~~
A multitude of more IDs can be found, but I found most not worthwile to track:
Adds: shockwave jump, Knockback jump, Auto attack, evading knockback,
Skorvald: Target for Combustion Rush, Solar bolt (red balls on the ground)

**Artsariiv**:
All add attacks except the _Vault_ by the big adds aren't worthwile tracking (imho), but there are at least 10 of them.
~~_Vault_: CCing staff jump of big adds~~
~~_Slam_: Vault attack from boss (showing orange circle below it)~~
~~_Blinding Radiance_: Feared by overhead eye (see Skorvald)~~
_Death ray_: not trackable
~~_Teleport Lunge_: Triple jump to a corner after death rays~~
~~_Corporeal Reassignment_: Skull buff application.~~ The attack itself is percentage based and thus not tracked.
_Obliterate_: Both the expanding circle after phases and the many circular purple pillars going of afterwards are HP% based
_Mib Ring_: Purple Goo below Arts and Split phase bosses is HP% based
~~_Astral Surge_: Spiraling circles on the floor in a variety of different sizes~~
~~_Red Marble_: Knocking red marble released by Arts before her Slam and sometimes by adds as well.~~
~~_Spark_: Failed to bounce the globola Marble properly, tracked via Spawn mechanic.~~
Normal red bullets from the boss aren't worthwile imho.

**Arkk**:
~~_Horizon Strike_: Rotating pizza attack~~
~~_Diffractive Edge_: 5 Cones in front of him~~
~~_Solar Fury_: Red overhead balls (or stood in their fields)~~
~~_Focused Rage_: Cone Knockback following overhead crosshair~~
~~_Starburst Cascade_: Floating expanding/contracting Ring attack~~
~~_Overhead Smash_: Overhead Smash~~
~~_Corporeal Reassignment_: Skull buff application~~ (hit can't be tracked, HP% based)
~~_Cosmic Meteor_: Better known as Temporal Realignment or Green; buff application~~ (hit can't be tracked, HP% based)
~~_Fixate_~~ and _Explode_: See Skorvald. All four fixates are different IDs so technically one could track which bloom attached to whom but i grouped them all together for now.
~~_Blinding Radiance_: Feared by overhead eye~~
~~_Breakbar_: Fail tracked by taking too long to break it.~~
_Small Ball_: Single red ball leaving purple fields behind, not sure if worth tracking
~~_Overhead Smash (Archdiviner)_: …~~
~~_Solar Stomp_: Evading stomp (last phase~~)
~~_Rolling Chaos_: small arrow following CC marble~~
~~_Cosmic Streaks_: DDR started death ray mechanic~~
~~_Spinning Cut_: Dazing auto by Gladiator~~
~~_Pull Charge_: Pull from Gladiator, failing tracked by taking too long~~
~~_Whirling Devastation_: Attack after Gladiator pull.~~
_Plunge_: Gladiator smashes his sword into the ground (Mesmer GS 3)

All the small add's attacks aren't worthwile to track, I feel? Same goes for the other AAs of the gladiator.
Maybe track the fields of the Archdiviner?

**Comment by LunusLupus** [comment]
This can ofc also be used for suggestions for raid mechanics that aren't currently tracked.

**Comment by EliphasNUIT** [comment]
You did a PR recently on that, could you specify which mechanics you did implement tracking for on that list so that we can eventually discuss if we need more or not? Thanks.

**Comment by LunusLupus** [comment]
Done

**Comment by EliphasNUIT** [comment]
Should we close this? I think we are pretty good on 99cm and 100cm mechanics. We can open a new dedicated issue if one day we get a new CM.

**Comment by LunusLupus** [comment]
Yes, I think that's a sensible action.
