### ISSUE TITLE
Sorting by Crit , Scholar, etc seems bugged 

### ISSUE THREAD

**Issue by Platapoop** [baaron4/GW2-Elite-Insights-Parser#152]
See https://dps.report/CYQP-20180910-223248_dei

If you sort by crit, it doesn't seem to sort correctly. Click the down/up arrow to sort and it seems to sort it incorrectly. 

My guess is that it tries to sort by total damage effected by crits, but it sorts by alphabetical order (555 > 499999 because the first digit, 5, is greater than 4), instead of lexical order (49999> 555).

**Comment by EliphasNUIT** [comment]
Fixed in #144
