### ISSUE TITLE
Wing 6 Boss 2 Error

### ISSUE THREAD

**Issue by dhanrahl** [baaron4/GW2-Elite-Insights-Parser#174]
Don't have an EVTC just yet (getting it soon as mine broke), but boss 2 of the new wing has 2 Boss IDs, which GW2EI is having trouble displaying correctly as it only focuses on the group who keeps attacking the main Boss ID, while secondary Boss ID returns no data DPS on boss.

**Comment by EliphasNUIT** [comment]
We didn't do any update for W6 so they are treated as a "generic/unknown" log, not really an error, 1.7.0.0 just does not know "who" is that encounter.

**Comment by dhanrahl** [comment]
Alright, we were not sure if it was just the parser not being able to manage multiple Boss IDs since there hasn't been a fight yet that has more than 1 main boss that requires a group split. It will recognize the first boss (arcdps Dev client has added IDs), but after the fight phases to the 2nd boss it has no targeted data, only area/overall damage data until the group(s) returns to the main boss.

**Comment by EliphasNUIT** [comment]
The issue has been fixed with #244. I'll release it after some polishing/minor updates/documentation updates.
