### ISSUE TITLE
Error while performing background operation.  

### ISSUE THREAD

**Issue by Dante4** [baaron4/GW2-Elite-Insights-Parser#18]
When i try to convert any of logs i get this error 
https://imgur.com/b9RzZej
After i tried to look into code (not my job to mess with it, i know, but it seemed like it very specific error, that only i met with), that part is what fail program for me:
https://imgur.com/11g6l1N
https://imgur.com/Qmmautl

**Comment by baaron4** [comment]
Looks like it failed when trying to get your elite spec from the GW2 API. It may be down. Im going to rework that so it stores the specs locally and itll be another file that needs periodic updates. Just so that it works even when API is down

**Comment by baaron4** [comment]
In the case that the class isnt standard (any currently known elite specs) it will now only search the API if it is up

**Comment by Dante4** [comment]
If you mean last version, it still crash for me. The only thing that helped me to use this parser is manually add this

**Comment by Dante4** [comment]
If you mean last version, it still crash for me. The only thing that helped me to use this parser is manually add this :
[spoiler]
case 1:
                            return "Mesmer";
                        case 2:
                            return "Necromancer";
                        case 3:
                            return "Revenant";
                        case 4:
                            return "Warrior";
                        case 5:
                            return "Druid";
                        case 6:
                            return "Engineer";
                        case 7:
                            return "Daredevil";
                        case 8:
                            return "Ranger";
                        case 9:
                            return "Revenant";
                        case 10:
                            return "Mesmer";
                        case 11:
                            return "Warrior";
                        case 12:
                            return "Revenant";
                        case 13:
                            return "Guardian";
                        case 14:
                            return "Revenant";
                        case 15:
                            return "Revenant";
                        case 16:
                            return "Guardian";
                        case 17:
                            return "Elementalist";
                        case 18:
                            return "Berserker";
                        case 19:
                            return "Necromancer";
                        case 20:
                            return "Thief";
                        case 21:
                            return "Engineer";
                        case 22:
                            return "Warrior";
                        case 23:
                            return "Mesmer";
                        case 24:
                            return "Mesmer";
                        case 25:
                            return "Ranger";
                        case 26:
                            return "Elementalist";
                        case 27:
                            return "Dragonhunter";
                        case 28:
                            return "Thief";
                        case 29:
                            return "Engineer";
                        case 30:
                            return "Ranger";
                        case 31:
                            return "Elementalist";
                        case 32:
                            return "Ranger";
                        case 33:
                            return "Ranger";
                        case 34:
                            return "Reaper";
                        case 35:
                            return "Thief";
                        case 36:
                            return "Warrior";
                        case 37:
                            return "Elementalist";
                        case 38:
                            return "Engineer";
                        case 39:
                            return "Necromancer";
                        case 40:
                            return "Chronomancer";
                        case 41:
                            return "Elementalist";
                        case 42:
                            return "Guardian";
                        case 43:
                            return "Scrapper";
                        case 44:
                            return "Thief";
                        case 45:
                            return "Mesmer";
                        case 46:
                            return "Guardian";
                        case 47:
                            return "Engineer";
                        case 48:
                            return "Tempest";
                        case 49:
                            return "Guardian";
                        case 50:
                            return "Necromancer";
                        case 51:
                            return "Warrior";
                        case 52:
                            return "Herald";
                        case 53:
                            return "Necromancer";
                        case 54:
                            return "Thief";
                        case 55:
                            return "Soulbeast";
                        case 56:
                            return "Weaver";
                        case 57:
                            return "Holosmith";
                        case 58:
                            return "Deadeye";
                        case 59:
                            return "Mirage";
                        case 60:
                            return "Scourge";
                        case 61:
                            return "Spellbreaker";
                        case 62:
                            return "Firebrand";
                        case 63:
                            return "Renegade";
[/spoiler]

**Comment by Dante4** [comment]
If you mean last version, it still crash for me. The only thing that helped me to use this parser is manually add this 

>                         case 1:
                            return "Mesmer";
                        case 2:
                            return "Necromancer";
                        case 3:
                            return "Revenant";
                        case 4:
                            return "Warrior";
                        case 5:
                            return "Druid";
                        case 6:
                            return "Engineer";
                        case 7:
                            return "Daredevil";
                        case 8:
                            return "Ranger";
                        case 9:
                            return "Revenant";
                        case 10:
                            return "Mesmer";
                        case 11:
                            return "Warrior";
                        case 12:
                            return "Revenant";
                        case 13:
                            return "Guardian";
                        case 14:
                            return "Revenant";
                        case 15:
                            return "Revenant";
                        case 16:
                            return "Guardian";
                        case 17:
                            return "Elementalist";
                        case 18:
                            return "Berserker";
                        case 19:
                            return "Necromancer";
                        case 20:
                            return "Thief";
                        case 21:
                            return "Engineer";
                        case 22:
                            return "Warrior";
                        case 23:
                            return "Mesmer";
                        case 24:
                            return "Mesmer";
                        case 25:
                            return "Ranger";
                        case 26:
                            return "Elementalist";
                        case 27:
                            return "Dragonhunter";
                        case 28:
                            return "Thief";
                        case 29:
                            return "Engineer";
                        case 30:
                            return "Ranger";
                        case 31:
                            return "Elementalist";
                        case 32:
                            return "Ranger";
                        case 33:
                            return "Ranger";
                        case 34:
                            return "Reaper";
                        case 35:
                            return "Thief";
                        case 36:
                            return "Warrior";
                        case 37:
                            return "Elementalist";
                        case 38:
                            return "Engineer";
                        case 39:
                            return "Necromancer";
                        case 40:
                            return "Chronomancer";
                        case 41:
                            return "Elementalist";
                        case 42:
                            return "Guardian";
                        case 43:
                            return "Scrapper";
                        case 44:
                            return "Thief";
                        case 45:
                            return "Mesmer";
                        case 46:
                            return "Guardian";
                        case 47:
                            return "Engineer";
                        case 48:
                            return "Tempest";
                        case 49:
                            return "Guardian";
                        case 50:
                            return "Necromancer";
                        case 51:
                            return "Warrior";
                        case 52:
                            return "Herald";
                        case 53:
                            return "Necromancer";
                        case 54:
                            return "Thief";
                        case 55:
                            return "Soulbeast";
                        case 56:
                            return "Weaver";
                        case 57:
                            return "Holosmith";
                        case 58:
                            return "Deadeye";
                        case 59:
                            return "Mirage";
                        case 60:
                            return "Scourge";
                        case 61:
                            return "Spellbreaker";
                        case 62:
                            return "Firebrand";
                        case 63:
                            return "Renegade";

**Comment by Dante4** [comment]
If you mean last version, it still crash for me. The only thing that helped me to use this parser is manually add this 
<p>
                        case 1:
                            return "Mesmer";
                        case 2:
                            return "Necromancer";
                        case 3:
                            return "Revenant";
                        case 4:
                            return "Warrior";
                        case 5:
                            return "Druid";
                        case 6:
                            return "Engineer";
                        case 7:
                            return "Daredevil";
                        case 8:
                            return "Ranger";
                        case 9:
                            return "Revenant";
                        case 10:
                            return "Mesmer";
                        case 11:
                            return "Warrior";
                        case 12:
                            return "Revenant";
                        case 13:
                            return "Guardian";
                        case 14:
                            return "Revenant";
                        case 15:
                            return "Revenant";
                        case 16:
                            return "Guardian";
                        case 17:
                            return "Elementalist";
                        case 18:
                            return "Berserker";
                        case 19:
                            return "Necromancer";
                        case 20:
                            return "Thief";
                        case 21:
                            return "Engineer";
                        case 22:
                            return "Warrior";
                        case 23:
                            return "Mesmer";
                        case 24:
                            return "Mesmer";
                        case 25:
                            return "Ranger";
                        case 26:
                            return "Elementalist";
                        case 27:
                            return "Dragonhunter";
                        case 28:
                            return "Thief";
                        case 29:
                            return "Engineer";
                        case 30:
                            return "Ranger";
                        case 31:
                            return "Elementalist";
                        case 32:
                            return "Ranger";
                        case 33:
                            return "Ranger";
                        case 34:
                            return "Reaper";
                        case 35:
                            return "Thief";
                        case 36:
                            return "Warrior";
                        case 37:
                            return "Elementalist";
                        case 38:
                            return "Engineer";
                        case 39:
                            return "Necromancer";
                        case 40:
                            return "Chronomancer";
                        case 41:
                            return "Elementalist";
                        case 42:
                            return "Guardian";
                        case 43:
                            return "Scrapper";
                        case 44:
                            return "Thief";
                        case 45:
                            return "Mesmer";
                        case 46:
                            return "Guardian";
                        case 47:
                            return "Engineer";
                        case 48:
                            return "Tempest";
                        case 49:
                            return "Guardian";
                        case 50:
                            return "Necromancer";
                        case 51:
                            return "Warrior";
                        case 52:
                            return "Herald";
                        case 53:
                            return "Necromancer";
                        case 54:
                            return "Thief";
                        case 55:
                            return "Soulbeast";
                        case 56:
                            return "Weaver";
                        case 57:
                            return "Holosmith";
                        case 58:
                            return "Deadeye";
                        case 59:
                            return "Mirage";
                        case 60:
                            return "Scourge";
                        case 61:
                            return "Spellbreaker";
                        case 62:
                            return "Firebrand";
                        case 63:
                            return "Renegade";
</p>

**Comment by Dante4** [comment]
If you mean last version, it still crash for me. The only thing that helped me to use this parser is manually add this 
<details>
                        case 1:
                            return "Mesmer";
                        case 2:
                            return "Necromancer";
                        case 3:
                            return "Revenant";
                        case 4:
                            return "Warrior";
                        case 5:
                            return "Druid";
                        case 6:
                            return "Engineer";
                        case 7:
                            return "Daredevil";
                        case 8:
                            return "Ranger";
                        case 9:
                            return "Revenant";
                        case 10:
                            return "Mesmer";
                        case 11:
                            return "Warrior";
                        case 12:
                            return "Revenant";
                        case 13:
                            return "Guardian";
                        case 14:
                            return "Revenant";
                        case 15:
                            return "Revenant";
                        case 16:
                            return "Guardian";
                        case 17:
                            return "Elementalist";
                        case 18:
                            return "Berserker";
                        case 19:
                            return "Necromancer";
                        case 20:
                            return "Thief";
                        case 21:
                            return "Engineer";
                        case 22:
                            return "Warrior";
                        case 23:
                            return "Mesmer";
                        case 24:
                            return "Mesmer";
                        case 25:
                            return "Ranger";
                        case 26:
                            return "Elementalist";
                        case 27:
                            return "Dragonhunter";
                        case 28:
                            return "Thief";
                        case 29:
                            return "Engineer";
                        case 30:
                            return "Ranger";
                        case 31:
                            return "Elementalist";
                        case 32:
                            return "Ranger";
                        case 33:
                            return "Ranger";
                        case 34:
                            return "Reaper";
                        case 35:
                            return "Thief";
                        case 36:
                            return "Warrior";
                        case 37:
                            return "Elementalist";
                        case 38:
                            return "Engineer";
                        case 39:
                            return "Necromancer";
                        case 40:
                            return "Chronomancer";
                        case 41:
                            return "Elementalist";
                        case 42:
                            return "Guardian";
                        case 43:
                            return "Scrapper";
                        case 44:
                            return "Thief";
                        case 45:
                            return "Mesmer";
                        case 46:
                            return "Guardian";
                        case 47:
                            return "Engineer";
                        case 48:
                            return "Tempest";
                        case 49:
                            return "Guardian";
                        case 50:
                            return "Necromancer";
                        case 51:
                            return "Warrior";
                        case 52:
                            return "Herald";
                        case 53:
                            return "Necromancer";
                        case 54:
                            return "Thief";
                        case 55:
                            return "Soulbeast";
                        case 56:
                            return "Weaver";
                        case 57:
                            return "Holosmith";
                        case 58:
                            return "Deadeye";
                        case 59:
                            return "Mirage";
                        case 60:
                            return "Scourge";
                        case 61:
                            return "Spellbreaker";
                        case 62:
                            return "Firebrand";
                        case 63:
                            return "Renegade";
</details>

**Comment by Dante4** [comment]
If you mean last version, it still crash for me. The only thing that helped me to use this parser is manually add this 
<details>
````Csharp
                        case 1:
                            return "Mesmer";
                        case 2:
                            return "Necromancer";
                        case 3:
                            return "Revenant";
                        case 4:
                            return "Warrior";
                        case 5:
                            return "Druid";
                        case 6:
                            return "Engineer";
                        case 7:
                            return "Daredevil";
                        case 8:
                            return "Ranger";
                        case 9:
                            return "Revenant";
                        case 10:
                            return "Mesmer";
                        case 11:
                            return "Warrior";
                        case 12:
                            return "Revenant";
                        case 13:
                            return "Guardian";
                        case 14:
                            return "Revenant";
                        case 15:
                            return "Revenant";
                        case 16:
                            return "Guardian";
                        case 17:
                            return "Elementalist";
                        case 18:
                            return "Berserker";
                        case 19:
                            return "Necromancer";
                        case 20:
                            return "Thief";
                        case 21:
                            return "Engineer";
                        case 22:
                            return "Warrior";
                        case 23:
                            return "Mesmer";
                        case 24:
                            return "Mesmer";
                        case 25:
                            return "Ranger";
                        case 26:
                            return "Elementalist";
                        case 27:
                            return "Dragonhunter";
                        case 28:
                            return "Thief";
                        case 29:
                            return "Engineer";
                        case 30:
                            return "Ranger";
                        case 31:
                            return "Elementalist";
                        case 32:
                            return "Ranger";
                        case 33:
                            return "Ranger";
                        case 34:
                            return "Reaper";
                        case 35:
                            return "Thief";
                        case 36:
                            return "Warrior";
                        case 37:
                            return "Elementalist";
                        case 38:
                            return "Engineer";
                        case 39:
                            return "Necromancer";
                        case 40:
                            return "Chronomancer";
                        case 41:
                            return "Elementalist";
                        case 42:
                            return "Guardian";
                        case 43:
                            return "Scrapper";
                        case 44:
                            return "Thief";
                        case 45:
                            return "Mesmer";
                        case 46:
                            return "Guardian";
                        case 47:
                            return "Engineer";
                        case 48:
                            return "Tempest";
                        case 49:
                            return "Guardian";
                        case 50:
                            return "Necromancer";
                        case 51:
                            return "Warrior";
                        case 52:
                            return "Herald";
                        case 53:
                            return "Necromancer";
                        case 54:
                            return "Thief";
                        case 55:
                            return "Soulbeast";
                        case 56:
                            return "Weaver";
                        case 57:
                            return "Holosmith";
                        case 58:
                            return "Deadeye";
                        case 59:
                            return "Mirage";
                        case 60:
                            return "Scourge";
                        case 61:
                            return "Spellbreaker";
                        case 62:
                            return "Firebrand";
                        case 63:
                            return "Renegade";
````
</details>

**Comment by Dante4** [comment]
In my case, i simple can't access GW2API without VPN. So when i try to parse this log 
https://drive.google.com/file/d/13qhtuRaSGhCgAx6CrlnfoZrfEyYLuGHb/view?usp=sharing
without whole case inside "if" it give me error.

**Comment by baaron4** [comment]
I mainly ask becasue is_elite = 0 indicates that they are using a non elite spec class so it will never reach the API part. If it was created during HoT your elite spec is then your profession +9. If the log was created in PoF then it just switches to using the actual specialization ID from the API to indicate your elite. So it should only be reaching the API code if you are using a new elite spec. Meaning there must be an error in the log

**Comment by Dante4** [comment]
I get is_elite = 40

**Comment by baaron4** [comment]
Its another locally stored file. Like skilllist itll have to be updated with the API when a new expack rolls around but that can always be done on my end
