### ISSUE TITLE
Missing Combat Replay Mechanics/Attacks

### ISSUE THREAD

**Issue by EliphasNUIT** [baaron4/GW2-Elite-Insights-Parser#194]
__Wing 1__:
- VG is ok
- Gorseval:
    - ~~Slam attack~~
- Sabetha:
    - ~~Flamewall -> rotating rectangle actor (new actor)~~
    - ~~Kernan's shotgun thingy -> Pie actor~~
    - ~~Knuckles' breakbar -> usual breakbar signal (growing circle)~~
    - ~~Karde's flamethrower -> Pie actor~~

__Wing 2__:
- Sloth:
    - ~~Breath attack~~
- Matthias:
    - ~~Hadouken - a single rectangle should be enough to signal it, trying to get the velocity of the attack, detecting that it hits the wall, etc would be too complex just for an attack~~

__Wing 3__:
- KC
     - ~~Green circle around green phantasms~~
     - ~~Fixations from adds/KC -> line actor (new actor)~~
- Xera:
     - Half moon mechanic -> pie actor
     - One shot mechanic -> growing circle on the arena

__Wing 4__:
- Cairn:
    - ~~Sword attack -> rotating rectangle actor~~
    - ~~Black wave attack -> doughnut actor~~
- MO:
    - ~~Yellow tiles -> rectangle actor~~ Won't be done
    - ~~Shield on jade armors -> circle actor~~
    - ~~Jade armor explosion~~
- Samarog:
    - ~~Human/Jotun fixation -> line actor~~
    - ~~Shockwave -> shockwave actor?~~ Won't be done
    - ~~Sweep -> pie actor~~ Won't be done
- Deimos is ok

__Wing 5__:
- ~~SH~~
- River of Souls:
   - ~~Bomb rings around Hollowed Bombers~~
   - ~~Walls~~
   - Line between Enervator and Desmina
   - Desmina bubble
- Broken King
   - Broken king's cone attack
- Soul Eater
   - ~~Vomit~~
   - ~~Soul transformation~~
   - ~~Breakbar~~
- Eyes
   - Laser attack
   - Fear attack
   - Minotaur effect zone
- Dhuum:
    - ~~Shackles -> line actor~~
    - ~~correct lesser death marks' position~~
    - ~~Greens~~
    - ~~Stealth on reapers~~

__Wing 6__:
- CA:
    - ~~Lasers on cm (we need scepter position tracking for that) -> line actor~~  Impossible for now
    - ~~Shield on boss -> circle actor~~
    - ~~Player shield~~
- Largos:
    - ~~Bubble -> circle actor~~
    - ~~Water zone drop debuff -> circle actor~~
    - ~~Water zone  -> growing circle actor~~
    - ~~Shockware -> shockwave actor~~
    - ~~Boon clone -> rectangle actor~~
    - ~~CC phases~~
    - ~~World eater attack on CM -> growing circle~~
- Qadim:
    - ~~all breakbars~~
    - ~~all shockwave attacks~~
    - ~~Qadim's fiery cone attacks -> pie actor~~
    - ~~Qadim's knockback attacks -> pie actor~~
    - ~~Wyvern's wing attack~~
    - ~~Wyvern's breath attack~~
    - ~~Wyvern's sweep attack~~
    - Signal teleporting attacks on legendary adds
    - Bouncing balls for CM, if possible

~~For the day we start animating Qadim's arena:~~
~~- triangle actors~~

**Comment by LunusLupus** [comment]
Dhuum: Shackles? (line actor)
Qadim: despawning platforms? (triangle actor)
Bouncing Ball in CM might be nice, but needs a bit of investigation how the pattern is and when it is reset/starts.

**Comment by LunusLupus** [comment]
Also, what about Cairn's doughnut? Even though fewer and fewer groups even see it, it's theoretically a thing.

**Comment by EliphasNUIT** [comment]
Updated

**Comment by EliphasNUIT** [comment]
Updated

**Comment by LunusLupus** [comment]
Since we may do River now :wink: :

* River of Souls
  * Bomber Circles: Filling Circle; ~480 radius, taking 3.5 seconds to explode
  * Player Bombs: Filling Circle: ~100 radius, dropping after 2 seconds, exploding 1 second later (not sure if detectable)
  * Desmina Bubble: Unfilled Circle: ~360 radius
  * Walls: Rotated Rectangle: best guess: ~480x160
  * Spatial Rift pulls: Line actor (might be a bit overkill though).

**Comment by EliphasNUIT** [comment]
You got the ids of those mechanics?

**Comment by LunusLupus** [comment]
Well, for some i got them, they are noted in the other issue. Will have a look for the others. Flomix got some as well i think. (E.g. walls)

**Comment by EliphasNUIT** [comment]
Updated for Dhuum and River of Souls

**Comment by EliphasNUIT** [comment]
Updated for W5 Statues

**Comment by LunusLupus** [comment]
Wing 7:
- Adina:
  - Cone Auto attacks
  - Players with tectonic upheveal
  - Quantum Quake (Hide behind pillars)
  - Diamond Palisade
  - Stone Death ray
  - Radiant Blindness on players
  - Tank (possible?)

- Sabir: 
  - Both Breakbars
  - Knockback beams
  - Fatal Tornado Aoes
  - small tornado lightning bars? Might be overkill and/or hard to code
  - Full stacks/SAK on players
  - Tank (possible?)

- Qadim:
  - Both tether types
  - Caustic Chaos (+ Caustic Corrosion); arrow attack + debuff
  - Ether Strikes (Cone)
  - Force of Havoc (Street)
  - All Fire/Magma fields (pylons and player generated)
  - Protective Bubble in CM?
  - Force of Retaliation (Knockback nova)
  - Residual impact (3 enlarging strikes)
  - Ruinous Nova (Wipe attack if pylons aren't broken)
  - Orbs?
  - ~~Tank~~

**Comment by EliphasNUIT** [comment]
Let's open issues by encounter/wings from now on.
