### ISSUE TITLE
Mechanic - Dhuum shackles only show 1 of the 2 shackle ends

### ISSUE THREAD

**Issue by MarsEdge** [baaron4/GW2-Elite-Insights-Parser#21]
The skill id is correct, but the actual shackle event has the source agent connected to the destination agent as the 2 end of the shackle. Currently, only the source player of the event is tracked. If a player is the destination of the shackle event, they will go untracked. You can see this in the dps graph as only 1 player appears to be shackled at a time.

**Comment by baaron4** [comment]
Added a check for this type of mechanic. Thank you
