### ISSUE TITLE
Twin Largos combat replay background missing

### ISSUE THREAD

**Issue by BackIsBachus** [baaron4/GW2-Elite-Insights-Parser#237]
**Describe the bug**

**To Reproduce**
1. Obtain a Twin Largos log (labelled as Nikare)
2. Parse it
3. Go to Combat Replay
4. See "The image you are requestion does not exist or is no longer available imgur.com" instead of the fight background

**Screenshots**
<img width="715" alt="gw2_largos_elite_bug" src="https://user-images.githubusercontent.com/6058550/47885177-04808f80-de34-11e8-81b8-e9378245e79e.PNG">

**Browser**
Firefox, Chrome

**IMPORTANT: Provide Files**
[20181101-214050.evtc.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/2540425/20181101-214050.evtc.zip)
[20181101-171334.evtc.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/2540426/20181101-171334.evtc.zip)

https://dps.report/nU8N-20181101-171334_twins
https://dps.report/sEIy-20181101-214050_twins

**Comment by EliphasNUIT** [comment]
fixed in #238 

Will be released tomorow.
