### ISSUE TITLE
Dhuum cone/suck aoe mechanics are mis-labeled

### ISSUE THREAD

**Issue by MarsEdge** [baaron4/GW2-Elite-Insights-Parser#24]
"Cataclysmic Cycle" (id 48398) is when a player touches the center aoe during suction, not the cone. Touching the center during suction does not appear to be listed in the supported mechanics.

"Slash" (id 47561) is when someone is hit by the cone such that boons are ripped (not just getting pulled in a bit). This is different from "Scythe Swing" (id 47123) which is his auto-attack. (I don't get their naming scheme, but oh well)

**Comment by baaron4** [comment]
I knew dhuum mechanics naming felt off. Just wasnt sure where exactly thanks. Made the changes, they will be present in next build
