### ISSUE TITLE
Average Boon amount

### ISSUE THREAD

**Issue by DerpyMoa** [baaron4/GW2-Elite-Insights-Parser#26]
Hello,
Would be really useful for classes with boon mods to be able to see average boon amount in player summary or boon tab.

**Comment by EliphasNUIT** [comment]
This should be easily doable. Would it be okay for it to appear as a tooltip while hovering over the character name on the boon table? I can also put it on the boon graph of player tab to see its real time evolution if you think it's interesting.

**Comment by EliphasNUIT** [comment]
There you go:
![avgboons](https://user-images.githubusercontent.com/16018765/41097009-d0cadafc-6a56-11e8-90b0-b02712977e02.png)
And
![avgboons 2](https://user-images.githubusercontent.com/16018765/41097288-bb89730a-6a57-11e8-973a-fae5e2171a12.png)

**Comment by DerpyMoa** [comment]
Looks perfect. This way can check amount of boons during Weaver burst too.
