### ISSUE TITLE
Samarog Log Won't Parse

### ISSUE THREAD

**Issue by violetoctagon** [baaron4/GW2-Elite-Insights-Parser#286]
**Describe the bug**
Samarog log won't parse.

**To Reproduce**
Attempting to parse this log result in failure.

**Screenshots**
![eibug](https://user-images.githubusercontent.com/26983086/50136916-4469cd80-024e-11e9-8d12-0cadf6e55ebc.PNG)

**Browser**
If the issue s related to your browser please provide which one you are using
N/A

**IMPORTANT: Provide Files**
Add the EVTC and/or HTML of the log related to this issue

[logs.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/2689203/logs.zip)

**Comment by EliphasNUIT** [comment]
I have a fix in the work, I need to check if it has any negative impacts

**Comment by EliphasNUIT** [comment]
fixed in the lastest release
