### ISSUE TITLE
0.98 release bugs

### ISSUE THREAD

**Issue by DerpyMoa** [baaron4/GW2-Elite-Insights-Parser#31]
There's 2 bugs I noticed with the 0.98 release.
1. Some icons are broken as seen here: https://i.imgur.com/KRMrMud.png
2. Can't access Weaver Player Summary in this log: https://cdn.discordapp.com/attachments/355999179102748674/455626789008441354/20180610-225804_mo_kill.html
3. Idk if this is with 0.98 but Arkk boss icon is broken as well.

*EDIT* The MO log gives parser error when I use the Parser UI https://i.imgur.com/TCmu6wD.png
But if I use "open with" on log (like I used to) then log parses with the previous bug(s).
If you want the evtc file, https://cdn.discordapp.com/attachments/355999179102748674/455628935846297600/20180610-225804.evtc

**Comment by baaron4** [comment]
A pull request was just merged that fixed the weapon icons.
Will look at log once I get to a pc
Only icons for raid bosses are currently stored.

**Comment by EliphasNUIT** [comment]
It's the death recap. We were checking downs and ups beyond the lifespan of the boss apparently (I think because of the small cutscene after MO's death, during which the logging continues), so it detects that the warrior went down once, got up, died and then got rezzed. Fixing it.

**Comment by EliphasNUIT** [comment]
We can close this I think.
