### ISSUE TITLE
Qadim platform animation issues

### ISSUE THREAD

**Issue by EliphasNUIT** [baaron4/GW2-Elite-Insights-Parser#324]
From #323 - @Sejsel 

- Sometimes some actors do not render you open the combat replay and did not press play yet. It is not a lifetime issue. It can happen to platforms, it can happen to player icons, but at the same time it might not happen to their facings. It's weird, I have no clue what it's caused by.

- Either I am doing some math wrong or there is something very weird about drawing images, almost as if there was a transform that'd make coordinates of everything further apart in the x axis, but not y.

After spending quite a lot of time on this, there are two possible outputs. Prior to the change in #c871f38, there were vertical gaps between platforms

![Before](https://user-images.githubusercontent.com/998408/51790478-43ee1c00-2196-11e9-8dea-8e88d3eb246f.png)

In #c871f38, the platform image was changed to properly fill between the corners, but the image is no longer an equilateral triangle (although the vertices do form one in the game!). This looks somewhat better until the jumping puzzle phase where platforms rotate and it becomes obvious.

![After the change](https://user-images.githubusercontent.com/998408/51790508-9a5b5a80-2196-11e9-8a15-7d8973a5d3d2.png)

![In the jumping puzzle](https://user-images.githubusercontent.com/998408/51790533-ee663f00-2196-11e9-845c-e789d6ca9637.png)

It might be fixable by modifying the texture somehow, but I do not know how, feel free to fix this (please do!)

- Qadim combat replay performance is a bit worse than combat replay of other encounters, presumably due to rendering 12 more images each frame. Mostly noticeable on Firefox. Might look into that in the future. When platforms are not moving they wouldn't need to be rendered separately, but there may be better ways to improve performance.

**Comment by EliphasNUIT** [comment]
- Image on load issue
- Combat replay map rectangle size issue
- To investigate

**Comment by Sejsel** [comment]
The coordinate issues are fixed in #326.

This only leaves the performance concerns. I checked and I get similar performance in other replays such as Matthias (but not some others, like MO), so I believe it's unrelated to what I am doing at Qadim.

Actually, as I am writing this, I checked and it might be caused, or at least made worse by Facing actors enumerating through all its positions on every single draw. That should be mostly an issue further in a long fight.

**Comment by EliphasNUIT** [comment]
Yeah I see that rotation actor sends an array of [angle, time]. An easy fix would be at init converting that to an array of angle with the same length as times.
The performance will also take a hit if you open the details window at the same time. From what I measured that hits come from the huge amount of dom updates that are being done. I'll try to change that so that window gets has a lower refresh rate.

**Comment by EliphasNUIT** [comment]
Facing actor performance improvements in #328

**Comment by EliphasNUIT** [comment]
Well nothing remains regarding Qadim's platform animation here, so I'm closing it.
