### ISSUE TITLE
Critical hit ration lower than expected

### ISSUE THREAD

**Issue by BackIsBachus** [baaron4/GW2-Elite-Insights-Parser#33]
**Describe the bug**
While parsing a Dhuum log (will be attached) I see that Elvarli Kajuta (me) got 50% of critical hits while the same upload on [DPSreport](https://dps.report/6OPr-20180611-222043_dhuum) and [Gw2raidar](https://www.gw2raidar.com/encounter/FociManuscriptPerceivedNicestReaction) show me 83-85% which seem more realistic. I will try and parse the rest of my clean tomorrow to see if other number seem really off.

**To Reproduce**
1. Parse the log attached

[20180611-222043.evtc.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/2091964/20180611-222043.evtc.zip)

[20180611-222043_dhuum_kill.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/2091970/20180611-222043_dhuum_kill.zip)

Zipped the html too since Github don't want to upload it otherwise.

**Comment by baaron4** [comment]
This is due to crit chance looking at just the boss hits (for raidheroes/dpsreports) vs everything you hit (boss + adds the way EI is doing it) It looks like some adds arent critable and seriously lowering crit chance in that encounter. Could just default to showing boss only then showing all crits effected on hover?

**Comment by BackIsBachus** [comment]
Displaying the all crits with adds on hover seem like a good idea so that we have both data points.

**Comment by baaron4** [comment]
![showoff](https://user-images.githubusercontent.com/30677999/41810783-9310521c-76c9-11e8-8b6b-9663f16535f7.PNG)
Added a new tab for Boss and All. However I noticed that it results in 80+% range for your player in both tabs. Wondering if the issue was fixed in the mean time
