### ISSUE TITLE
JSON: Player's weapons array should include value "Unknown"/null

### ISSUE THREAD

**Issue by BrandonSchmitt** [baaron4/GW2-Elite-Insights-Parser#358]
I would like to see an empty weapon slot described as "Unknown" or `null`, just like in the HTML logs. Currently, e.g. `["Scepter", null, null, "Sword"]`, `["Scepter", "Sword", null, null]` and `["Scepter", null, "Sword", null]` all result in the same array: `["Scepter", "Sword"]`.
This is ambiguous. The HTML parser correctly differentiates the logs 1 and 2 (Scepter,Sword) from 3 (Scepter,Unknown/Sword,Unknown).
Similarly with `["Sword", null, "Greatsword", "2Hand"]` which is being reduced to `["Sword", "Greatsword", "2Hand"]`. Even though you can work it out by watching for the key word "2Hand" but it would make parsing the json easier if you could just interpret every two strings as one pair.

I guess simply removing the `.Where(w => w != null)` in the file [RawFormatBuilder.cs#L236](https://github.com/baaron4/GW2-Elite-Insights-Parser/blob/f448304f46d6d459bea9f03931ba22d861f6e070/LuckParser/Builders/RawFormatBuilder.cs#L236) should do the trick.

Attached some sample logs for my problem: [weapon-logs.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/3010981/weapon-logs.zip)

**Comment by EliphasNUIT** [comment]
Seems reasonable, will be changed in next.

Thanks.

**Comment by EliphasNUIT** [comment]
fixed in #359
