### ISSUE TITLE
Small Bug List

### ISSUE THREAD

**Issue by dhanrahl** [baaron4/GW2-Elite-Insights-Parser#4]
Will try to update this as our group discovers little errors instead of sending multiple reddit messages back and forth.

Noticed a few things:

1. Protection Boon uptime is 100% wonky, displaying 11mil+ percentage uptime (seen for Aegis and Vigor as well).
2. Banner of Strength tracking is missing.
3. Since Mirages do not use evades, there is no tracking for Mirage Cloak (their new evade); Skill ID: 40408
4. Some Mechanic tracking is off as well. Example would be a Samarog Parse for Shockwave gaining 87 triggers vs RH's reporting only 1 trigger. Some are realistic, others are not. Unsure if this is due to Aegis/Stab negating the mechanic vs taking the hit.

About all issues I can think of currently. As for suggestions:

1. Unified colour coding for tracking, or at least match the colour with the Damage Graph and the Personal graphs for consistancy.
2. Boons/Effects to add to tracking: Battle Presence (ID:554), Soothing Mist (ID:350), Pinpoint Distribution (ID:1984), Vampiric Aura (ID:30285), Assassin's Presence (ID:1802). Believe those are the major ones missing.
3. A personal request, would be for golem parses or maybe for Player views, to have a streamlined look that matches RH's layout simply for easier access to information. More access to statistics on such a personal level will be a great addition. 
4. Another personal request would be usage of this via command prompt/PowerShell to allow interactions with auto-uploaders and home-brewed parsing scripts.

While more data is the goal (and more data is always welcome, we need it), a more fluid UI will help with that as this develops further, and brings more people into the fold. Otherwise we look forward to where the development of this tool leads us data-hungry raiders.

**Comment by dhanrahl** [comment]
Quick follow up before bed: 

1. & 2 The BoS issue is with everything enabled through the parser, I should have included the parameters, my bad.

3. I do see that you have the skills as such, not familiar with the Ambush skills, but I do agree that flagging it as a skill activation of it's own is worth displaying for consistency to mirror other profession's evade.

4. It's a start at least, we've been without proper Raid 2 tracking since RH's creator vanished. Might be something to reach out with Martion Laboratories with and see if they're willing to collaborate, as they've got a pretty good mechanic plugin.

Suggestions:

1. The one that was brought to my attention was DH which displays as Hot Pink (?) on the Damage Graph, but yellow on the player summary. Minor detail for sure, but worth pointing out. I can go through tomorrow to comb through the rest just in case.

2. I would at least advocate for adding AP/PD on the list, as those 2 are pretty important buffs to keep track of, with the other 3 being beneficial for analyzing healing which I suppose could be less important if you're running into formatting issues.

3. My main idea behind this was for at least golem parses, was to circumvent the need to navigate tabs, but I wouldn't have any notion of the work involved, so merely a personal suggestion.

4. If it ends up being too much it is what it is, still a great tool.

**Comment by baaron4** [comment]
1. boons are a mess at present. I found one problem but it created a few more
2.done
2.Is now added to defenses table with dodges
Suggestion:
1. ya I just noticed it. spelled "DragonHunter" instead of "Dragonhunter" will be in next build
2.Added all the suggested ones to the table. Doesnt bloat it too-ish much
3. I saw the RH version of this. Havent started yet
4. Havent started yet

**Comment by dhanrahl** [comment]
Realized Battle Presence isn't the effect it puts on people, it's a specific Virtue of Resolve (ID:17046).

**Comment by dhanrahl** [comment]
Can you include the method it's using to parse from console to the Readme?

**Comment by baaron4** [comment]
Sure if your intrested its located here: 
https://github.com/baaron4/GW2-Elite-Insights-Parser/blob/24df62abfec74446a07816524a98b9d97d87d966/LuckParser/Program.cs#L15-L22

Ill get to work on adding instructions in the readme

**Comment by baaron4** [comment]
Im not tracking all mechanic types. Atm the only type of mechanic being tracked is if a player gains a buff, if a player gets hit by a certain skill, and if a player casts a skill onto another player. I also left this up for the golem mode. Ill just close it and have it referenced in the project To_dos
