### ISSUE TITLE
W7 - Combat Replay

### ISSUE THREAD

**Issue by EliphasNUIT** [baaron4/GW2-Elite-Insights-Parser#425]
Continuation of #194, @LunusLupus' post

Wing 7:
- Adina:
  - Stalagmites 
  - Players with tectonic upheveal
  - ~~Boulder Barrage (Hide behind pillars)~~
  - ~~Diamond Palisade (Adina reflect buff pre global radiant blindness + boulder barrage)~~
  - ~~Quantum Quake (rotating death ray)~~
  - ~~Radiant Blindness on players~~
  - Tank (possible?)
  - ~~Terraform (Shockwave that changes the arena)~~

- Sabir: 
  - ~~Both Breakbars~~
  - ~~Bolt Break (bomb like mechanic)~~
  - ~~Fury of the Storm~~
  - Dynamic Deterrent (Knockback beams)
  - ~~Unbridled Tempest (Shock wave)~~
  - ~~Fatal Tornado Aoes~~
  - small tornado lightning bars? Might be overkill and/or hard to code
  - Full stacks/SAK on players
  - Tank (possible?)

- Qadim:
  - ~~Both tether types~~
  - ~~Caustic Chaos (+ Caustic Corrosion); arrow attack + debuff~~
  - ~~Ether Strikes (Cone)~~
  - ~~Force of Havoc (Street)~~
  - ~~All Fire/Magma fields (pylons and player generated~~) (small CM player ones currently not implemented)
  - Protective Bubble in CM?
  - ~~Force of Retaliation (Knockback nova)~~
  - Residual impact (3 enlarging strikes)
  - Ruinous Nova (Wipe attack if pylons aren't broken)
  - ~~Orbs? (at least orbs on pylons via the powershare buff if not the orbs itself)~~
  - ~~Tornados in CM~~
  - ~~Tank~~

**Comment by LunusLupus** [comment]
Qadim:
- Force of Havoc is done
- Orbs were already done at an earlier update.

**Comment by LunusLupus** [comment]
Qadim:
- Caustic Chaos (+ Caustic Corrosion); arrow attack + debuff
- Ether Strikes (Cone)
- Force of Retaliation (Knockback nova)
