### ISSUE TITLE
Exception thrown because of a SetStackCenterPositions bug

### ISSUE THREAD

**Issue by Sejsel** [baaron4/GW2-Elite-Insights-Parser#427]
There's a rather significant bug in Statistics.SetStackCenterPositions().

On the following line,

https://github.com/baaron4/GW2-Elite-Insights-Parser/blob/719ebf7ef84c39098ea1c0304dba715bc7c82207/LuckParser/EIData/Statistics.cs#L280

the count of positions of the first player in the list is used, but that can be lower than positions of the others, so some positions are ignored.

 This later causes issues (IndexOutOfRangeException) when calculating average stack distance because `positions` and `stackCenterPositions` have different sizes.

Exception is thrown later here:
https://github.com/baaron4/GW2-Elite-Insights-Parser/blob/719ebf7ef84c39098ea1c0304dba715bc7c82207/LuckParser/EIData/Actors/Player.cs#L372

Don't have time to fix it myself now. I have a log this crashes on (the first player in the list is dead the whole fight), but am not allowed to share it. I can test a fix.

**Comment by EliphasNUIT** [comment]
I have used MarsEdge's log to test the fix, if it was indeed the same bug, should be fixed in 2.16.2.0

**Comment by Sejsel** [comment]
I have tested the log and it is indeed fixed now, after all the logs were pretty much the same.
