### ISSUE TITLE
Twisted Castle parsed as unknown encounter

### ISSUE THREAD

**Issue by knoxfighter** [baaron4/GW2-Elite-Insights-Parser#437]
**Describe the bug**
Twisted Castle is parsed as unknown encounter.
Example: https://dps.report/lx8N-20191120-212039_boss

This is parsed as general fight, it should be parsed as TC. 
As far as i see, the current BossID for TC is  `16247`. You use `4` currently.

**Comment by EliphasNUIT** [comment]
Hello,

16247 is the id of the haunted statues, it is basically a hack to start the logging process on arc's side as there are no "natural" ids to trigger TC logging. 4 is a custom id I use as there are no actual boss npc during that encounter, basically the same idea Delta uses for WvW logs, they come with boss id 1. 2 and 3 are already taken on my side for other purposes.

Your dps.report link is using 2.18.1.0, the TC fight support has been added recently with 2.19.0.0. You need to wait for dps report to update its executable.

**Comment by knoxfighter** [comment]
Oh, ok thanks alot for that information :)
I wish i would understand that better, im closing this, since it is already fixed :)
