### ISSUE TITLE
Command line execution of latest version throws an exception.

### ISSUE THREAD

**Issue by LunusLupus** [baaron4/GW2-Elite-Insights-Parser#44]
Using the latest version normally (opening the executable and dragging files into the UI+parsing) works fine but if executed from the command line via 'GuildWars2EliteInsights.exe "filename.evtc" ', I receive the following error (losely translated from German, but the error description should be correct):

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance to an object
at LuckParser.MainForm.LvFileList_AddItems(String[] filesArray) in I:\LuckParser\LuckParser\MainForm.cs:Line 288.
at LuckParser.MainForm..ctor(String[] args) in I:\LuckParser\LuckParser\MainForm.cs:Line 55.
at LuckParser.Profram.Main(String[] args) in I:\LuckParser\LuckParser\Program.cs:Line 27

The previous versions worked fine with the command line.

**Comment by EliphasNUIT** [comment]
That was a recent regression that escaped from our attention. It is already fixed in the current master branch and we should get a release soon.

**Comment by EliphasNUIT** [comment]
Wait I've just checked, the bug is fixed in 1.1c but present in 1.1b, can you confirm you reproduced the issue in 1.1c? (it was released soon after 1.1b)

**Comment by LunusLupus** [comment]
Seems like I missed the 1.1c release, my bad (only read phases and thought it was the version I had, 1.1b). Command line works fine with current version. But the naming convention seems to have changed? The files produced are now date.etvc_boss_success.html, the ".evtc" had been removed (and that's probably intended) in previous versions.

**Comment by EliphasNUIT** [comment]
@cordbleibaum I believe this came from you?

**Comment by EliphasNUIT** [comment]
Rollback on naming convention #45 (it is as before now)
