### ISSUE TITLE
Masterless Gadgets

### ISSUE THREAD

**Issue by EliphasNUIT** [baaron4/GW2-Elite-Insights-Parser#455]
Tentative:
- ~~Add master to engineer turrets~~ Missing harpoon
- ~~Add master to warrior banners~~
- ~~Add master to Jacaranda roots~~
- ~~Sylvari Racial turrets~~
- More?

**Comment by Sejsel** [comment]
I will go through all my logs to see what gadgets typically inflict damage, I'll let you know when I have the results.
