### ISSUE TITLE
Parse Multiple Log Files simultaneously

### ISSUE THREAD

**Issue by anewhomegw2** [baaron4/GW2-Elite-Insights-Parser#459]
**Is your feature request related to a problem? Please describe.**
GW2 Elite Insights processes files in sequential order one at a time, which can be slow when processing many log files and has no low resource utilization (cpu, disk io) as a result.

When parsing add a line 'Processing N files concurrently: N files process/X files remaining to process - processing duration <hh:mm:ss>; estimated time remaining <hh:mm:ss>' or something similar when parsing is being run to the GUI.  It is currently only generating around 20 logs/minute - I have around 7320 log files to be reprocessed - 366 mins required = 6.1 hrs at the current processing speed.  The machine I am running this on is easily capable of running 5-10 logs concurrently, running at 5 logs concurrently would reduce processing time down to 73.2 mins.

**Describe the solution you'd like**
Under the parsing option - add 'Process N log files simultaneously' - where N can be adjusted.
When parsing the logs it would simultaneously process N files at once.  This default value should be 5. (5x6-15% = 30% - 75% cpu utilisation (max) ).

**Describe alternatives you've considered**
Running multiple copies of elite insights - this is clunky as it requires sorting out the logs to be processed manually and cannot monitor a folder for new log files.

**Additional context**
Currently it only uses around 6-15% cpu and has spikes on disk utilization which is very low for the reads/writes and has plenty of overhead for running faster.

**Comment by EliphasNUIT** [comment]
This is actually a feature I have removed recently as there is already multi threaded code in the parsing process (some under option, the "use multi threading on log processing") but also the upload processes. It was causing a lot of ressource management issues where the upload process could hang then die if too many logs were processed at the same time, severely slowing down everything. Unfortunately we have never measured the gains you expect to get either, it is faster but not N times faster. 

I'm afraid exposing the N would be more problematic for me, as most users won't be familiar with the concept of cores and threads, I'd rather manage it myself depending on the capacities of the computer, like using half the available threads.

I need to see how I can introduce it back in the future but I have no immediate plans to work on that.

**Comment by anewhomegw2** [comment]
I'm already using the multi-threading on log processing option (enabled) - that's 6 hrs to complete the log processing with the option enabled.

**Comment by EliphasNUIT** [comment]
I have introduced the option in https://github.com/baaron4/GW2-Elite-Insights-Parser/releases/tag/v2.23.0.0 (May 2020) and it is also compatible with discord/upload options with https://github.com/baaron4/GW2-Elite-Insights-Parser/releases/tag/v2.28.1.0 (November 2020).

Time estimation is unfortunately not possible as the parsing time does not depend only on file size but is also heavily influenced by how condition heavy the fight was. A mirage rich Twin Largos or Matthias log will take longer than an slb + guard rich Adina log at equal size.

Does the current implementation satisfy your request?
