### ISSUE TITLE
Sunqua boss considered as failed because Ai never really die

### ISSUE THREAD

**Issue by aeris** [baaron4/GW2-Elite-Insights-Parser#498]
Sunqua boss stay alive at the end with <1% HP.
This generate a failed report but the fight is really a success.

EVTC available here : https://drop.infini.fr/r/TuKvFDoHfG#dGP483kYHJ0BJ2Wk3cSyKEKBlUWSh1Oo8f1CklluGFY=
![2020-10-19_11-04](https://user-images.githubusercontent.com/51246/96424870-9ccbd680-11fb-11eb-95cb-1fd3dbb1d808.png)

**Comment by EliphasNUIT** [comment]
Hello,

It seems you are not running the latest version (2.28 released 15 days ago at the time of writing). Your log parses fine locally and dps.report with correct time and success detection.

Can you please double check?

**Comment by aeris** [comment]
Yeah sorry… Download the zip on the wrong path (browser add .1 at the end :P) and so unpack the wrong old version…
All is good!
