### ISSUE TITLE
Broken boss health graphs

### ISSUE THREAD

**Issue by DJ4ddi** [baaron4/GW2-Elite-Insights-Parser#5]
Hi there.

I threw a bunch of logs at the parser for testing and the boss health graph always comes out like this (tested for every challenge mode boss):

![graph](https://user-images.githubusercontent.com/1696102/38762325-f1462c7e-3f8a-11e8-8866-0bb5f871d372.png)

Looks cool, but isn't very helpful. This also breaks auto scale so all other graphs are barely visible. DPS graphs by themselves seem to be working correctly.

Here is the log file for this specific example: [20180304-223927.evtc.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/1909827/20180304-223927.evtc.zip)
And this is the HTML the parser produced: [20180304-223927_mo_kill.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/1909829/20180304-223927_mo_kill.zip)

Logs were generated using version v.91 under Windows 10 (64 bit). The screenshot of the graph was taken in Firefox, but it looks the same in Chrome.

Have fun,
Addi

**Comment by baaron4** [comment]
I couldnt replicate it but after looking at the html I can see commas are in place of periods. It effected a couple of graphs, boss health being one of them. So Im adding a Globalization change at the start of the main program.

**Comment by baaron4** [comment]
I cant test for this issue, but I changed the worker thread globalization to US. It should fix the issue.

**Comment by DJ4ddi** [comment]
Can confirm, fixed in v0.931.
