### ISSUE TITLE
Arkk wrong success detection (false negative)

### ISSUE THREAD

**Issue by Sejsel** [baaron4/GW2-Elite-Insights-Parser#511]
Clearly a kill, marked as failure.

Found when comparing results with https://github.com/gw2scratch/evtc/.

[20200819-025857.evtc.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/5647881/20200819-025857.evtc.zip)

**Comment by EliphasNUIT** [comment]
Already fixed in #510

**Comment by Sejsel** [comment]
Oh, cool, thanks! :)
