### ISSUE TITLE
Discord WebHook URL from Discord Client Recognized as Invalid

### ISSUE THREAD

**Issue by TiffanyDiVita** [baaron4/GW2-Elite-Insights-Parser#512]
If you create a Discord WebHook URL from the Discord client itself and choose the "Copy URL" button, it will generate a link starting with:

https://discord.com/api/webhooks/

If you use this as a WebHook URL within the Elite Insights program, it will throw this error:

Couldn't send embed: The given webhook Url was not in a valid format. The webhook Id could not be parsed.
Parameter name: webhookUrl

This is the new domain on which Discord WebHooks are hosted. Old webhooks begin with:

https://discordapp.com/api/webhooks

The discordapp.com URL works fine with Elite Insights.

The recognized domain for webhooks in GW2EI needs to be updated from discordapp.com to discord.com, or it should recognize both as valid as either seems to work on Discord's end for the time being.

**Comment by EliphasNUIT** [comment]
I'm using a third party lib Discord.Net for webhook related stuff,
It looks like they did the necessary changes but they have not made a release on NuGet yet. Is the only difference the switch between discordapp.com to discord.com? If so I can simply do a replace while waiting for a new Discord.Net release.

**Comment by EliphasNUIT** [comment]
I think I'll rather for the "submodule" road on git. I'll keep you updated.

**Comment by EliphasNUIT** [comment]
Should be fixed in #514
