### ISSUE TITLE
Allow external/CDN usage for js & css

### ISSUE THREAD

**Issue by aeris** [baaron4/GW2-Elite-Insights-Parser#520]
Currently GW2EIP use hardcoded `./EliteInsights-2.28.0.js` & `./EliteInsights-CR-2.28.0.js` path for resources.
It could be cool to have an option to specify the expected path for those resources and so allowing shared path like with a CDN (`https://cdn.example.org/EliteInsights-CR-2.28.0.js`) or logs in subfolders using a common absolute path (`/assets/EliteInsights-2.28.0.js`).

**Comment by EliphasNUIT** [comment]
I'll add this to my backlog but this is going to be very low priority compared to other tasks I've planified.

**Comment by EliphasNUIT** [comment]
Added in #540 thanks to @tschoeck

**Comment by aeris** [comment]
ohhhhhhhhhhhh :heart_eyes: 
Thanks a lot @tschoeck
