### ISSUE TITLE
Deimos displaying CM health on normal mode <10%

### ISSUE THREAD

**Issue by Endaris** [baaron4/GW2-Elite-Insights-Parser#537]
**Describe the bug**
In logs parsed with the current version Deimos NM health always shows as 42804900 if the 10% phase was reached. 
In logs using version 2.23 normal mode deimos shows as 37388210 instead if the 10% phase was reached which should be the correct value.

**To Reproduce**
Should be reproducable with any Deimos NM log that reaches 10%. Parse attached log as a sample.
[20210122-221015.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/5862948/20210122-221015.zip)
Output on dps.report: https://dps.report/nd0l-20210122-221012_dei

**Cause**
This was likely caused by [this commit](https://github.com/baaron4/GW2-Elite-Insights-Parser/commit/d8c173ff7cf31a5ef7d258ab3c76dee7d458b735) which changed CM evaluation from a bool-like int to an enum but didn't change the evaluation of `res > 0` along with the introduction of the enum, causing any Deimos to reach 10% to always apply the CM 10% health value.

**Comment by EliphasNUIT** [comment]
Thanks for the report!

I've left a comment in your PR.
