### ISSUE TITLE
Incorrectly logged bomb triggers on Dhuum

### ISSUE THREAD

**Issue by Endaris** [baaron4/GW2-Elite-Insights-Parser#567]
I have written a small tool for myself that essentially creates a mechanics log from a bunch of evtc logs parsed into json using elite insights
Using it to check the mechanics for a Dhuum training I noticed that the manual bomb trigger gets logged sometimes when
a) the bomb gets stripped during soulsplit
or very often when
b) the encounter ends because a reaper dies

I'm not 100% sure if the reaper dying really makes this behaviour consistent but it does look like it for now. Can provide more logs if needed. Not sure if this is a parser or evtc issue.

https://dps.report/RIru-20210608-210654_dhuum [20210608-210654.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/6642990/20210608-210654.zip) Manual bomb trigger logged 30ms before knockback damage
https://dps.report/WLDj-20210608-221438_dhuum [20210608-221438.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/6642996/20210608-221438.zip) Manual bomb trigger logged 80ms before end of encounter due to a reaper dying
https://dps.report/iXQP-20210608-222530_dhuum [20210608-222530.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/6642997/20210608-222530.zip) Manual bomb trigger logged 100ms before end of encounter due to a reaper dying

**Comment by EliphasNUIT** [comment]
Hello,

This is not a simple issue to fix. EI checks that the bomb buff has been lost while it still had time remaining. There is no way to reliably know why a buff was lost. 
EI is checking if in a small time window, the player with the bomb got hit with Greater Death Mark or not, but I guess the window is too small and sometimes the check fails, I'll make the window bigger.
I'll see what I can do for the reaper dying situation.

**Comment by EliphasNUIT** [comment]
Should be fixed with def2cb2301791e5c6da1c44f964a63704e8a098b and e70a97d97d321533ff031554471200832d3e954d.

**Comment by EliphasNUIT** [comment]
Should be fixed since 2.35.0.0
