### ISSUE TITLE
Getting stuck on older (possibly bugged) logs

### ISSUE THREAD

**Issue by oRRs** [baaron4/GW2-Elite-Insights-Parser#590]
**Describe the bug**
Instead of throwing an error, EI gets stuck with 25% CPU usage (1 core) indefinitely on many of my old logs. This causes issues with batch-processing of all logs e.g. with the gw2wingman uploader.

**To Reproduce**
Drag attached log (remove .zip extension, forced by GitHub) on GuildWars2EliteInsights.exe

[20170717-205623.zevtc.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/7155742/20170717-205623.zevtc.zip)

**Comment by EliphasNUIT** [comment]
This seems to be coming from a very old bug where a player was reported as a pet of another player but also the master of that player, causing a cyclic relation and an infinite loop when trying to find the master.
Fixed in 270cb9a0260f8c8a47fbbc60e3712969c52508ce.

**Comment by EliphasNUIT** [comment]
Fixed in 2.38.0.0.
