### ISSUE TITLE
Missing Class Specific Buffs

### ISSUE THREAD

**Issue by Linkaaaaa** [baaron4/GW2-Elite-Insights-Parser#595]
Main list:

https://github.com/baaron4/GW2-Elite-Insights-Parser/tree/master/GW2EIEvtcParser/EIData/ProfHelpers

- Necromancer:

1. ~~https://wiki.guildwars2.com/wiki/Plague_Sending_(effect)~~
2. ~~https://wiki.guildwars2.com/wiki/Vampiric_Mark (gets applied on the target by https://wiki.guildwars2.com/index.php?title=Blood_Bond and  https://wiki.guildwars2.com/index.php?title=Signet_of_Vampirism , not sure if it should be part of this list)~~ Was covered via "Signet of Vampirism (Active)", renamed to Vampiric Mark
3. https://wiki.guildwars2.com/wiki/Plague_(effect) (historical plague effect before plaguelands)

- Reaper:

1. ~~https://wiki.guildwars2.com/index.php?title=%22Nothing_Can_Save_You!%22 has unblockable effect, might be already logged as general effect?~~ Covered via generic unblockable effect https://wiki.guildwars2.com/wiki/Unblockable_(effect) (36781)
2. ~~https://wiki.guildwars2.com/index.php?title=Infusing_Terror_(effect)~~

- Scourge:

1. ~~https://wiki.guildwars2.com/index.php?title=Path_Uses~~

- Guardian:

1. ~~https://wiki.guildwars2.com/wiki/Force_of_Will_(effect)~~
2. ~~https://wiki.guildwars2.com/wiki/Virtue_of_Resolve_(effect) has 3 different types, core, with https://wiki.guildwars2.com/wiki/Absolute_Resolve and with https://wiki.guildwars2.com/wiki/Battle_Presence , not sure if all of them are already included within the single resolve effect at line 72 of https://github.com/baaron4/GW2-Elite-Insights-Parser/blob/master/GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs~~ Covered via Battle Presence variants, properly renamed to Virtue of Resolve

- Elementalist:

1. ~~https://wiki.guildwars2.com/wiki/Mist_Form_(effect)~~
2. ~~https://wiki.guildwars2.com/wiki/Stone_Heart_(effect)~~
3. ~~https://wiki.guildwars2.com/wiki/Electrified_Tornado~~
4. ~~https://wiki.guildwars2.com/wiki/Whirlpool~~
- Weaver:

1. ~~https://wiki.guildwars2.com/wiki/Grinding_Stones_(effect)~~

- Mesmer:

1. ~~https://wiki.guildwars2.com/wiki/Reflection~~
2. ~~https://wiki.guildwars2.com/wiki/Illusion_of_Life_(effect) (it's on friendly target)~~

- Engineer:

1. https://wiki.guildwars2.com/index.php?title=Tornado_(effect)
2. https://wiki.guildwars2.com/wiki/Electrified_Tornado_(effect)
3. ~~https://wiki.guildwars2.com/wiki/Big_Boomer_(effect)~~
4. ~~https://wiki.guildwars2.com/index.php?title=Health_Insurance (not sure if the med kit bonus is an effect)~~
5. https://wiki.guildwars2.com/index.php?title=Rampage_(effect)

- Revenant:

1. ~~https://wiki.guildwars2.com/index.php?title=Steadfast_Rejuvenation~~ (the effect page doesn't exist "[&BvzQAAA=]There is no article linked with this ID (53500) yet. If you know what skill this chat link links to, please add the ID to the article or create it if it does not exist yet."
2. ~~https://wiki.guildwars2.com/index.php?title=Selfless_Amplification~~ (just as above, the effect page doesn't exist)

- Herald:

1. ~~Rising momentum is currently located in the revenant page instead of herald, line 91~~

- Warrior:

1. ~~https://wiki.guildwars2.com/wiki/Signet_of_Ferocity~~
2. ~~https://wiki.guildwars2.com/wiki/Adrenal_Health_(effect)~~

- Spellbreaker:

1. ~~https://wiki.guildwars2.com/wiki/Disenchantment (on target)~~
2. ~~https://wiki.guildwars2.com/wiki/Magebane_Tether_(effect)~~

- Not a class effect but it's relevant for WvW logs (not sure where to check it)
~~https://wiki.guildwars2.com/wiki/Minor_Borderlands_Bloodlust~~
~~https://wiki.guildwars2.com/wiki/Major_Borderlands_Bloodlust~~
~~https://wiki.guildwars2.com/wiki/Superior_Borderlands_Bloodlust~~

**Comment by Linkaaaaa** [comment]
- Tempest

https://wiki.guildwars2.com/index.php?title=Heat_Sync_(effect) (gets applied on other targets and never yourself)

**Comment by Linkaaaaa** [comment]
- Dragonhunter

https://wiki.guildwars2.com/index.php?title=Hunter%27s_Mark (applies on enemy targets)

**Comment by EliphasNUIT** [comment]
Added:
- Tranquil for Revenant
- Tactical Reload and Overcharged Cartridges for Bladesworn

**Comment by EliphasNUIT** [comment]
Closing this, will open a new one if necessary.
