### ISSUE TITLE
Issues with mechanics appearing more than should be possible

### ISSUE THREAD

**Issue by Chris-Bitler** [baaron4/GW2-Elite-Insights-Parser#6]
We ran the logs for a group we ran with on VG tonight and noticed some oddities in the mechanics portion. You can find the log [here](http://v-l.pw/imgs/20180413-203548_vg_kill.html). The two issues we noticed:

Unstable magic spike (teleport circles) are being counted as going off even when the person evades/dodges/otherwise blocks it from actually teleporting them.
The pillar attunement ones are showing multiple attunements in each phase for people who got teleported into a different area (IE the person with 4 total attunements despite there being two splits)

Everything considered this is a great parser and very useful (especially with the detection for things like greens, which no other parse I've seen has). It just has some rough edges. 😄

**Comment by baaron4** [comment]
I just added exclusion of blocked hits from mechanics. However for attunements procing multiple times I dont think I can. Just looking at one of my own groups logs I think what happens is if a player gets downed they lose the attunement then regain it after getting resurrected.
