### ISSUE TITLE
Add phasing and combat replay for Mordremoth

### ISSUE THREAD

**Issue by Linkaaaaa** [baaron4/GW2-Elite-Insights-Parser#603]
Add phasing to the target ID 15884

CM health: 9569560
NM health: 2355584

at 90%, 80%, 70%, 60%, 25%: 762 Determined
at 25%: Determined (from this point onwards it can be killed in 1 phase, it depends on the group damage, split phasing per burn phase)
at 1%: Determined (i think) and requires stomping to finish the encounter

The encounter has multiple allied and enemy npcs, might require multiple logs to get every ID case

Attached: 
Normal mode log broke into 2 parts for me, hasn't generated any for Areki
Challange Mote log, including death at 7 minutes for me, you will respawn in a chamber out of combat but the other players will remain in the fight, it should log correctly

Linus might create a basic combat replay for this issue later down time line.

[Mordremoth.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/7562362/Mordremoth.zip)

**Comment by LunusLupus** [comment]
CR arena: https://i.imgur.com/HHDVDPb.png

**Comment by EliphasNUIT** [comment]
Added in #605 
Just send the missing ids my way when you got them (Missing evil canach, evil trahearn and evil tybalt)
