### ISSUE TITLE
EoD Strikes - Combat Replay

### ISSUE THREAD

**Issue by EliphasNUIT** [baaron4/GW2-Elite-Insights-Parser#624]
__Aetherblade Hideout__
- Mai trin Cone AoEs.
- Mai Trin rectangle AoEs.
- Scarlet's smashes.
- SAK.
- Blues.
- Orange Circle spreads.
- Greens.

__~~Xunlai Junkyard~~__
https://github.com/baaron4/GW2-Elite-Insights-Parser/blob/master/GW2EIEvtcParser/EncounterLogic/Strikes/EndOfDragons/XunlaiJadeJunkyard.cs

__~~Kaineng Overlook~~__
https://github.com/baaron4/GW2-Elite-Insights-Parser/blob/master/GW2EIEvtcParser/EncounterLogic/Strikes/EndOfDragons/KainengOverlook.cs

__~~Harvest Temple~~__
https://github.com/baaron4/GW2-Elite-Insights-Parser/blob/master/GW2EIEvtcParser/EncounterLogic/Strikes/EndOfDragons/HarvestTemple.cs

__Old Lion's Court__
- Reds.
- Red In/Out attack.
- Green Push.
- Green Boomerang.
- Blue Pull.
- Blue TP Select.
- Blue spread AoE.
- Knight Wipe AoEs (breakbar).

**Comment by Linkaaaaa** [comment]
With #931 and #935 we can consider this complete
