### ISSUE TITLE
Rotation Text Output

### ISSUE THREAD

**Issue by SeparGW2** [baaron4/GW2-Elite-Insights-Parser#627]
I generally get better results using text more than graphics for many things.  

I would like to be able to show the player summary basic and advanced rotations in a tabular form that could exported or copied in csv format.  Columns would be Skill Name | Time (s) | Duration (ms) | Comment | Skill Graphic

Skill Name: Skill Name or "Weapon Swap"
Time: Elapsed time in seconds from start
Duration: Time in milliseconds to execute skill
Comment: blank or one of: Hit without aftercast; Hit with full aftercast;  Attack canceled before completing; Instant cast;  Unknown state.
Skill Graphic: To allow those that do well with images to benefit from this version as well as the original

**Describe alternatives you've considered**
Manually transcribing values from graphic display and mouse over texts.  Tedious, subject to error and tedious, not to mention tedious..

**Additional context**
A (very small) portion of https://dps.report/bz6U-20220306-210357_golem, Deusici advanced rotation.
![Proposed Text Version of EVTC file](https://user-images.githubusercontent.com/31021448/157541295-7c88319a-c323-4a05-bc21-d6a936a1d8b6.png)

**Comment by EliphasNUIT** [comment]
Couldn't this be done by fetching the JSON from dps.report and displaying it in the way you wish?
There are already too many rotation displays on the HTML: simple rotation, advanced rotation, rotations, player/target tab graphs, combat replay. Not sure I want to add an extra one.

**Comment by SeparGW2** [comment]
I will give that a try.
