### ISSUE TITLE
Harvest Temple invalid health in champion phases

### ISSUE THREAD

**Issue by Sejsel** [baaron4/GW2-Elite-Insights-Parser#636]
**Describe the bug**
If you wipe within the Void Time Caster phase, the fake Mordremoth agent is not created even though it's already there. This results in the health on the fake Jormag agent being set to wrong health.

**Screenshots**
![image](https://user-images.githubusercontent.com/998408/160579209-0775c55a-bc33-4d40-9f6a-ac425e15daa2.png)
![image](https://user-images.githubusercontent.com/998408/160579263-9cadc50c-bb19-4dd3-a562-5c50f19ad2bd.png)

**Provide Files**
Can send privately.

**Comment by Sejsel** [comment]
To be more precise, the wipe needs to happen after the ball becomes CCable.

**Comment by EliphasNUIT** [comment]
I'm definitively going to need the log for it, I'm not 100% certain I see what's going on

**Comment by EliphasNUIT** [comment]
Fixed in 9ef0b1ea0297f41f1b96412e24d13b0a87e89a26.
