### ISSUE TITLE
PersonalBuffs in HTML output but not in JSON output

### ISSUE THREAD

**Issue by Drevarr** [baaron4/GW2-Elite-Insights-Parser#691]
**Describe the bug**
JSON output doesn't have a complete list of `personalBuffs`, but HTML output has a complete table including the missing buffs in JSON output.  Attached examples are missing Med Kit, Static Shield and Absorb

I only noticed it for scrapper, when collecting total personalBuffs uptime across 2 hours of logs. Need to review the other profession.
 
**To Reproduce**
1. process attached zetvc files with v2.51.0
2. Compare HTML output to JSON

**Screenshots**

![personalBuffsHTML](https://user-images.githubusercontent.com/16168556/220465593-36dfd4fe-b77e-4367-a160-9bb2c8a87a15.png)
![personalBuffsJSON](https://user-images.githubusercontent.com/16168556/220465607-c0dcedff-9fd5-4108-b5dd-6cd0b3da072a.PNG)

**IMPORTANT: Provide Files**

EVTC, JSON and HTML examples attached
[personalBuffsIssue.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/10798035/personalBuffsIssue.zip)

**Comment by EliphasNUIT** [comment]
Fixed in e825a67.
