### ISSUE TITLE
Application crashing, but it's not visible why

### ISSUE THREAD

**Issue by Quadellupine** [baaron4/GW2-Elite-Insights-Parser#7]
https://cdn.discordapp.com/attachments/303623405876412417/435184071895941130/unknown.png

I wish I knew why. Happens with all logs of all ages at random, if I reparse it works again. Prevents mass parsing because it constantly crashes.

**Comment by baaron4** [comment]
Looks like its dieing when it start to write to the html. This is the most intensive part of the program. I can run some stress tests and see what might be the biggest cause.

**Comment by baaron4** [comment]
Seems to be related to fail runs crashing in certain situations. I found one issue that mightve been the cause (A divide by max damage for boss health when no one has even done any damage) There may be more cases like this. If you encounter more please send em the evtc it fails on

**Comment by Dante4** [comment]
Title same, but moment when it happens is different. 
Status: Reading Binary
https://imgur.com/a/4yaaXex

https://drive.google.com/file/d/1eBL9GBuEILzHrZBUlCSXIjN550JSjFj8/view?usp=sharing
https://drive.google.com/file/d/1_-sDbAChAJYDDrCAOZu73KY2Gcue8cVy/view?usp=sharing

**Comment by baaron4** [comment]
Using V0.95 I was able to parse the files no problem. Would the issue be your version of windows? that almost looks like XP

https://drive.google.com/file/d/17NEls3JOtC8l9hM0lvf8XQKz-qzUaWJ0/view?usp=sharing
https://drive.google.com/file/d/1mkRGXeNQUw17uEh49T1ypouxdfeUOJ3Q/view?usp=sharing

**Comment by Dante4** [comment]
Windows 7 x64 Pro - Classic theme with classic shell.

**Comment by Dante4** [comment]
Last version fixed this for me

**Comment by baaron4** [comment]
Cool mustve been one of the smaller bugs that got fixed recently.

**Comment by Dante4** [comment]
This log Crash app at Writing HTML for me

https://drive.google.com/file/d/1Jso5ARPAqKadIKHSpcS1ayIkmnu2Pssc/view?usp=sharing

It still generate HTML but i can't access some of tabs
