### ISSUE TITLE
[Issue] Harbinger's simple rotation doesn't line break when entering shroud

### ISSUE THREAD

**Issue by Linkaaaaa** [baaron4/GW2-Elite-Insights-Parser#743]
Harbinger's doesn't show a weapon swap and line break when entering shroud, also looks like some skills could appear before the entering shroud icon.

![AVwcMWJ](https://user-images.githubusercontent.com/23245218/236331060-c04a0cbc-7a96-404d-907e-7789d71c5e12.png)

**Comment by EliphasNUIT** [comment]
Is harbinger shroud does provoc a weapon swap like the others, it needs to be added to IsSwap.
Nothing much can be done about skills appearing before.

**Comment by EliphasNUIT** [comment]
Fixed in effa92e890933b3d106df0c68abee40991499f87
