### ISSUE TITLE
[Issue] Kodans Strike can display incorrect combat time

### ISSUE THREAD

**Issue by Linkaaaaa** [baaron4/GW2-Elite-Insights-Parser#744]
If a player is in combat when the encounter begins, the timer won't reset correctly.

Video + Example Log:
https://streamable.com/h86g7b 
https://gw2wingman.nevermindcreations.de/log/20230429-160749_supkodbros_fail
[20230429-160749.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/11408693/20230429-160749.zip)

Link to the discussion on the discord:
https://discord.com/channels/456611641526845473/718866714527399976/1101858669915816097

**Comment by EliphasNUIT** [comment]
Is this still an issue? Latest should have improvements in regards to this but no idea if it is sufficient.

**Comment by Linkaaaaa** [comment]
From the test i just did it looks about right, i'll close it
