### ISSUE TITLE
Dhuum affliction / affliction damage mechanics are backwards

### ISSUE THREAD

**Issue by MarsEdge** [baaron4/GW2-Elite-Insights-Parser#75]
Currently, the Dhuum 'Arcing Affliction DMG' and 'Arcing Affliction' mechanics are reversed. 'Arcing Affliction DMG' shows the number of afflictions a player has received and 'Arcing Affliction' shows the number of damage ticks from exploded afflictions. This is also visible on the dps graph.

See https://dps.report/WPbe-20180705-232558_dhuum for an example

**Comment by EliphasNUIT** [comment]
Thanks, i'll correct it ^^

**Comment by EliphasNUIT** [comment]
fixed in #76
