### ISSUE TITLE
Move imgur images to a safer hosting platform

### ISSUE THREAD

**Issue by Sejsel** [baaron4/GW2-Elite-Insights-Parser#756]
Imgur has announced its new [ToS](https://help.imgur.com/hc/en-us/articles/14415587638029-Imgur-Terms-of-Service-Update) which includes deleting "inactive" images from anonymous accounts (for now). There is a bunch of images hosted on imgur, such as combat replays...

There was also an imgur outage yesterday and a lot of images stopped loading.

[imgur images in the repo](https://github.com/search?q=repo%3Abaaron4%2FGW2-Elite-Insights-Parser%20imgur.com&type=code)

**Comment by Linkaaaaa** [comment]
Wouldn't the solution be to just have an account?
Also since the images are references on all logs, they probably shouldn't be showing as "inactive" to them, hopefully at least.

Would be safer to do a mass-download of all imgur.com image references though.

**Comment by EliphasNUIT** [comment]
All images I upload there are tied to my account, not sure about the ones added recently by @Linkaaaaa and @Zerthox.
@LunusLupus are CR images tied to an account?

**Comment by Linkaaaaa** [comment]
Mine aren't tied to an account, also if you really want to be cheeky we could have a channel on elite insights discord to upload images and reference from there lol

**Comment by EliphasNUIT** [comment]
I trust Discord even less than imgur.

Could you update your images then please? Or list them to me so then I can add them to my account to centralize them on a single location.

**Comment by Linkaaaaa** [comment]
I will have to backtrack all of them, don't have them downloaded on my pc anymore

**Comment by EliphasNUIT** [comment]
If you can list them via going through your own commits, I can do the rest. I'll let you decide on how to handle it.

**Comment by Zerthox** [comment]
Only images added by me are here https://github.com/baaron4/GW2-Elite-Insights-Parser/pull/753/commits/13192ace821c3f70517f2dfa87e7628ee24744c2 (not merged yet). They are linked to an account. Let me know and I will update them to centralized versions before its merged.

**Comment by LunusLupus** [comment]
My images are connected to my imgur account. But we can also group them all under your account if you prefer, @EliphasNUIT

**Comment by EliphasNUIT** [comment]
All imgur images have been moved to non anonymous accounts. I'm closing this for now, we will see in the future should their stance on the subject changes.

As far outages, imgur has not been less reliable than the official API so far so I'm not very concerned with it at this time.
