### ISSUE TITLE
Duration of Conditions Cleansed Overstated

### ISSUE THREAD

**Issue by Drevarr** [baaron4/GW2-Elite-Insights-Parser#776]
**Describe the bug**
Over 2 million value for Duration of Conditions Cleansed against 26 conditions cleanses in a 55s long fight.

![image](https://github.com/baaron4/GW2-Elite-Insights-Parser/assets/16168556/a5877f13-15f8-45bd-bedd-f098aa1ea4a8)

**IMPORTANT: Provide Files**
Add the EVTC and/or HTML of the log related to this issue
[DurationOfConditionsCleansed-Zevtc-Json-Html.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/11943998/DurationOfConditionsCleansed-Zevtc-Json-Html.zip)

**Comment by Drevarr** [comment]
Possibly related issue, same log for `Duration of Boons Stripped`:

![image](https://github.com/baaron4/GW2-Elite-Insights-Parser/assets/16168556/aad50246-cdfd-4163-9146-0515567b5e47)

**Comment by Drevarr** [comment]
Additional logs with Duration of Cleanse and Strip anomalies.  Impacted player in log name.

[Additional Logs - Duration of Cleanse and Strip.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/11953117/Additional.Logs.-.Duration.of.Cleanse.and.Strip.zip)

**Comment by EliphasNUIT** [comment]
I have only looked at your first log so far, in the provided log I see a BuffRemove event Primal Clone removed one stack of bleeding from Grim Grooblin at 27156 ms. Said bleeding's duration was 2147482623 ms. As far as I can see, there are no parsing error in that log. As to what could possibly apply such a long bleed duration, I have no idea.

I will take a look at the other when I have the time but I suspect similar things.

For the boon strip my suspicion is that somebody stripped/corrupted a guardian's auto aegis and that has massively inflated the removed duration.

**Comment by Drevarr** [comment]
Interesting, thanks for the review.  It seems to be common enough to happen at least once per WVW rally (15-30 fights).  Blows out the boxplot charts for `duration of`.

Is this potentially something in the ArcDps side of things, or just an oddity from the game output?

**Comment by EliphasNUIT** [comment]
I'm closing this as whatever happened in those logs is not related to parsing.
