### ISSUE TITLE
List of Suggestions, small bugs

### ISSUE THREAD

**Issue by LunusLupus** [baaron4/GW2-Elite-Insights-Parser#8]
I just wanted to drop some ideas:

1. Mechanic markers are somewhat difficult to see as small dots over the dps graphs (sometimes they are even under them); maybe use bigger and/or non-filled markers?
2. Add downed/dead as markers on the damage graphs.
3. On Dhuum, Mortal Coil and Fractured Spirit always coincide since they are placed on the person at the same time. Maybe remove one of them?
4. The y-axis on the rotation graph has a scale from 0 to 2 but doesn't carry any information (if I am not mistaken) except casting boxes having smaller height for auto attacks. The boxes seem to go up over the course of the fight though. Maybe bring them all on the same level or make somehow visible what the y-axis represents.

Bugs ore odd behaviour:

5. A small thing that I also realized: Boon uptimes are considerabley lower than on both raidar and raid-heroes. And when looking at the boon graph under 'Player' it shows even less. I am quite sure on MO I can keep up 95%+ quickness, but the boon stats only show around 66% on myself and in the 'Player' boon graph there are only some spikes at the start of the fight and no more quickness at all after 40 seconds.
6. In the Boon graph under 'Player', Elementalists' Attunements seem to be active over the whole fight after the player has switched to them once. Same for some Signets and other Effects like "Blur" on Mesmer. Also, Banner of Discipline has two entries while Banner of Strength has none.

That sounds a bit negative overall but this parser is amazing already and I really like it. Will probably fully replace raid-heroes in my static once it's a bit more polished. If I have the time I will see if I can work on some of the changes myself though I haven't looked into the code at all so far.

**Comment by baaron4** [comment]
1. Added custom markers for all mechanics
2.Added
3. I like having as many options as possible. Yes they coincide but it should give the user info on how long it may have taken them to get all  the orbs they needed
4.Trying to fix this. It seems to be a plotly issue in stacking bar charts that overlap

5. and 6. Boons are acting wonky atm. Uptime is using a dated factory method and Im 100% positive if your native language isnt English it wont read them all (Im searching for their name instead of ID since it was quick and dirty) Ill be swapping to IDs to support all languages

**Comment by LunusLupus** [comment]
Thanks you so much for the update!

One small remark: it seems, some mechanics now use the same marker (noticed it on Matthias for Sacrifice and Corruption; at Dhuum for Green Orbs and Mark, Dip AoE and Big Dip Aoe).

What exactly do you mean by "give the user info on how long it may have taken them to get all the orbs"? Should the marker appear at the moment they come down? It looks more like they get the debuff when they go up (so at the same time as they take the green), but maybe I am misunderstanding that?

**Comment by baaron4** [comment]
Fixed the last dealio
