### ISSUE TITLE
Encounter related casts

### ISSUE THREAD

**Issue by Linkaaaaa** [baaron4/GW2-Elite-Insights-Parser#823]
List of skills that are encounters related to look into.

- [Sapper Bomb (Sabetha)](https://wiki.guildwars2.com/wiki/Sapper_Bomb) - Already Tracked
- [Purge (Slothasor)](https://wiki.guildwars2.com/wiki/Purge_(Slothasor))
- [Unstable Blood Magic (Matthias)](https://wiki.guildwars2.com/wiki/Unstable_Blood_Magic_(skill))
- [Over Here (Escort)](https://wiki.guildwars2.com/wiki/Over_Here!)
- [Intervention (Xera)](https://wiki.guildwars2.com/wiki/Intervention)
- [Celestial Dash (Cairn)](https://wiki.guildwars2.com/wiki/Celestial_Dash)
- [Claim (MO)](https://wiki.guildwars2.com/wiki/Claim)
- [Dispel (MO)](https://wiki.guildwars2.com/wiki/Dispel)
- [Protect (MO)](https://wiki.guildwars2.com/wiki/Protect)
- [Issue Challenge (SH)](https://wiki.guildwars2.com/wiki/Issue_Challenge)
- [Expel Energy (Dhuum)](https://wiki.guildwars2.com/wiki/Expel_Energy)
- [Conjured Protection (CA)](https://wiki.guildwars2.com/wiki/Conjured_Protection) - Already Tracked
- [Conjured Slash (CA)](https://wiki.guildwars2.com/wiki/Conjured_Slash) - Already Tracked
- [Flash Discharge (Sabir)](https://wiki.guildwars2.com/wiki/Flash_Discharge)
- [Flux Disruptor: Activate (QadimP)](https://wiki.guildwars2.com/wiki/Flux_Disruptor:_Activate) - Already Tracked
- [Flux Disruptor: Deactivate (QadimP)](https://wiki.guildwars2.com/wiki/Flux_Disruptor:_Deactivate) - Already Tracked
- [Nova Launch (Artsariiv)](https://wiki.guildwars2.com/wiki/Nova_Launch)
- [Hypernova Launch (Arkk)](https://wiki.guildwars2.com/wiki/Hypernova_Launch)
- Icebrood Saga SAKs - Already Tracked
- [Reverse the Polarity! (AH CM)](https://wiki.guildwars2.com/wiki/Reverse_the_Polarity!)
- [Purifying Light (Dagda)](https://wiki.guildwars2.com/wiki/Purifying_Light_(Dagda)) - Already Tracked

**Comment by EliphasNUIT** [comment]
Celestial Dash, Nova Launch and Hypernova Launch are movement skills, they shouldn't be put as an InstantCast.

Purge, Unstable Blood Magic and Dhuum bomb SAK (we could also add) are buff based, we can use that to detect the cast.
I believe Reverse the Polarity also comes with some buffs.

Issue Challenge applies a Fixation buff on the user but we would need to check two things: it is not the first buff and the moment of the application does not coincide with the other holder's death.

**Comment by Linkaaaaa** [comment]
Yeah the dashes skills would be done similarly to druid staff 3 if possible, mentioned it to zerthox earlier today, maybe not all of these are possible, just wanted to have a list to reference. I'll add dhuum's bomb to the list.

**Comment by EliphasNUIT** [comment]
There is already a mechanic to track manual dhuum bomb triggers so I know that one is at least possible =P
I suspect Purge and Unstable Blood Magic can be handled in a similar manner.

**Comment by EliphasNUIT** [comment]
As requested, everything has been added.
