### ISSUE TITLE
Gorseval 'Slam' can be double-counted

### ISSUE THREAD

**Issue by MarsEdge** [baaron4/GW2-Elite-Insights-Parser#86]
Gorseval's 'Slam' (name="Spectral Impact", id=31875) can 2 parts. 1st in an AoE around him and 2nd from his fist. If a player gets hit by the fist, they will also get hit by the AoE. Thus, they will have 2 combat events in a single slam. This means that the number of recorded hits can be up to 2x the number of failed dodges/aegis/whatever.

In https://dps.report/pv8m-20180718-211307_gors 'Teleri Casidhe' was hit by 16 slams, but Gorseval only had 8 skill activations for Spectral Impact. Is it possible to add some filtering such that the number of counted hits is concurrent with the number of failed mechanics?

**Comment by EliphasNUIT** [comment]
Wait, that Teleri guy, isn't he completely broken? no DPS, no boons, reaper with torch(???), in combat replay he is completly off.

**Comment by baaron4** [comment]
Lol look at his damage taken. Its like he took the bosses id or somthing. But his rotation is still there ish

**Comment by baaron4** [comment]
Can we get the EVTC to maybe find out if its arc or us causing the chaos?

**Comment by EliphasNUIT** [comment]
I can only see something like that happening if he had id == 0 (which should not happen)

**Comment by MarsEdge** [comment]
I posted the log on the Discord. I hadn't realized how many things were off about that necro. I know that for gors slams, I did have to add an icd to prevent it registering twice on occasion.
