### ISSUE TITLE
Might Overstack Numbers Grossly High Occasionally

### ISSUE THREAD

**Issue by Enko63** [baaron4/GW2-Elite-Insights-Parser#88]
I noticed this on a couple of other logs as well since that huge number stands out a lot on the CSV files.

https://gyazo.com/af9d2165db15f5c67439a583227a1b86

[20180716-224938.evtc.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/2217375/20180716-224938.evtc.zip)

**Comment by EliphasNUIT** [comment]
Fixed in https://github.com/EliphasNUIT/GW2-Elite-Insights-Parser/commit/2da68e7214cef4acec4900e89140cdc33dec1bdf
