### ISSUE TITLE
Avoid duplicate decoration metadata

### ISSUE THREAD

**Issue by Zerthox** [baaron4/GW2-Elite-Insights-Parser#899]
We often create multiple decorations for a single event (skill, effect etc.) and those decorations are then duplicated in their entirety every time it occurs. This leads to a lot of duplicate information.
Instead, we could store a single instance of metadata for the decorations and only repeat a way to reference the metadata (e.g. internal id) + lifespan + position/rotation each time it repeats.

**Comment by EliphasNUIT** [comment]
Closing this, implemented in 2.70.0.0
