### ISSUE TITLE
Wrong name for ID of Voice and Claw of the Fallen in EncounterID documentation

### ISSUE THREAD

**Issue by pv42** [baaron4/GW2-Elite-Insights-Parser#914]
**Describe the bug**
EncounterIDs.md has Freeze in the Strikes > Festivals category as 0x040101 and again in the Strikes > IBS category as 0x040203 while not having the Super Kodan Brothers at all. 

**To Reproduce**
Direct link to the doc file: https://github.com/baaron4/GW2-Elite-Insights-Parser/blob/master/EncounterIDs.md/#icebrood-saga

**Screenshots**
\-

**Browser**
\-

**IMPORTANT: Provide Files**
\-

**Comment by EliphasNUIT** [comment]
Fixed in 30ad52c.
