### ISSUE TITLE
"Effective Physical Damage Increase" for Seaweed Salad

### ISSUE THREAD

**Issue by towelcat** [baaron4/GW2-Elite-Insights-Parser#92]
I'm not sure if active foods are logged yet (or if it's even allowed), but it would still be nice to see what the contribution of seaweed salad was. Can easily just ignore it if you know you weren't running seaweed as well. Maybe put a movement % threshold before it displays it? (Assuming, again, that food isn't logged.)

**Comment by EliphasNUIT** [comment]
I mean we are logging scholar without checking if the player has the runes or not, we can do the same for seaweed, the data is already there.

**Comment by EliphasNUIT** [comment]
Done in my workspace. Will be in the next release.
