### ISSUE TITLE
Mechanic Sizes for Combat Replay

### ISSUE THREAD

**Issue by LunusLupus** [baaron4/GW2-Elite-Insights-Parser#99]
Mechanic sizes for combat replay (all in radius unless otherwise noted):
I also mentioned some mechanics that currently are not shown but could be implemented later.

**VG:**
~~_Seeker_: Correct~~
~~_Coloured Guardian Auras_: Seems correct~~

**Gorseval:**
~~_Souls Weakness Auras_: Closer to 240, I think? Not entirely sure~~

**Sabetha:**
~~_Timed Bombs_: Smaller than 300 but larger than 240, probably around 275-280?~~

**Sloth:**
~~_Slubling eating radius_ is closer to 180~~

**Matthias:**
~~_Corruption_: 180 radius~~
~~_Icy Patch_ 180-200 radius (pretty sure it's 200)~~
~~_Shield Bubble_: 250 radius (slightly larger than feedback bubble) not sure if size is relevant though~~
~~_Well of the Profane:_ seems correct~~
~~_Fire Tornado_: 80-100?~~
~~_Spirits_: 180~~
~~_Zealous Benediction_: 180 (for future reference)~~
~~_Storm Cloud:_ 240-300, closer to 240~~

**KC:**
~~_Tower Drop_: 400 radius (pretty much exactly 3 floor tiles, the quadratic ones, in diameter as seen here: https://youtu.be/BbxW2PtcHxM?t=40; one floor tile is roughly 270 units in diameter)~~
~~_Named Phantasms_: _Inner Circle_ (debuffing KC on death): 400 radius (seems same as tower drop)~~
~~_Outer Circle_ (white, causing merge sequence initiation when touching the other Phantasm): 600 radius~~
~~_Xera's Fury (Bombs)_: 550 radius (for future reference)~~
~~_Green circles_ in split phase (_Xera's Phantasm_): 210 radius~~

**Cairn:**
~~_Shared Agony_: 220 radius, slightly smaller than Tides of Rejuvenation as can be seen here: https://youtu.be/TWlbGvbs44c?t=46~~

**SH:**
~~_Inner doughnut_: probably closer to 400 radius 
see 360 radius in comparison (renegade utility) here: https://youtu.be/yce02S5j-u8?t=68
_Outer doughnut_: 800 radius~~
~~_Surging Souls (Walls)_: 660x240 units in size~~
~~_Golem death puddle_: closer to 400 radius
See comparison to 360 (renegade utility and time warp) here: https://youtu.be/yce02S5j-u8?t=156
Direct comparison to meteor shower (360 radius) shows it's at least a bit bigger, so most likely 400~~

**Dhuum:**
_Reaper green_: 300 radius (for future reference)
_Lesser Deathmark_:~480 radius. Compared to Healing Rain radius (which is actually 480, thanks for correct tooltips, ANet _cough_).
~~_Cataclysmic Cycle_:  300 radius. +- a few units but most likely exactly 300~~
~~_Last Phase Bubble_: Between 300 and 360 (see Timewarp and Eruption comparison here: https://youtu.be/cikoSyGpryE?t=202)~~
~~_Slash_: (Boon ripping cone): 850 radius, 60 degree opening angle (for future reference)~~

**Comment by EliphasNUIT** [comment]
If the cata cycle on Dhuum is around 300, the bubble should be slightly bigger then (like 40-60 units) no?

**Comment by LunusLupus** [comment]
The bubble is very difficult to see due to the effects going on in the 10% phase. I will try to verify it. Lesser Deathmark is definitly in the vicinity of that size, will try to get a good video example or screenshot.

**Comment by EliphasNUIT** [comment]
I've also checked on some combat replays, on all of them at least half of the raid would be eaten by it on that size xD And I even see people running inside it unscathed

**Comment by LunusLupus** [comment]
Running inside what unscathed? Lesser Deathmark?

**Comment by LunusLupus** [comment]
Ah, it's 450, not 540, my bad :laughing: I assumed the white AoE after casting Meteor shower would place meteors at the very edge and add the impact radius of these but apperently it only adds half of their radius. Could you check if 450 is a better estimate?

**Comment by EliphasNUIT** [comment]
Just for information, regarding Lesser Death Marks:
- The size given here is good
- The position on combat replay is wrong, it is not centered on the boss but just outside the hitbox (around 200) in the direction it's facing
